// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Allowance reason codes (UNCL5189 subset)
 * @version D.16B
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5189/
 * @enum
 * @category Peppol Values
 */
export const allowanceChargeReasonCodes = {
"41": "Bonus for works ahead of schedule",
"42": "Other bonus",
"60": "Manufacturer’s consumer discount",
"62": "Due to military status",
"63": "Due to work accident",
"64": "Special agreement",
"65": "Production error discount",
"66": "New outlet discount",
"67": "Sample discount",
"68": "End-of-range discount",
"70": "Incoterm discount",
"71": "Point of sales threshold allowance",
"88": "Material surcharge/deduction",
"95": "Discount",
"100": "Special rebate",
"102": "Fixed long term",
"103": "Temporary",
"104": "Standard",
"105": "Yearly turnover",

} as const;

/**
 * Keys of {@link allowanceChargeReasonCodes}.
 */
export type allowanceChargeReasonCodesKey = "41" | "42" | "60" | "62" | "63" | "64" | "65" | "66" | "67" | "68" | "70" | "71" | "88" | "95" | "100" | "102" | "103" | "104" | "105";
export const allowanceChargeReasonCodesKeys = [
  "41",
  "42",
  "60",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "70",
  "71",
  "88",
  "95",
  "100",
  "102",
  "103",
  "104",
  "105",
] as const satisfies readonly [allowanceChargeReasonCodesKey, ...allowanceChargeReasonCodesKey[]];
