// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Application Response type code (UNCL4343 Subset)
 * @version D.17A
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4343/
 * @enum
 * @category Peppol Values
 */
export const applicationResponseTypeCodes = {
"AB": "Message acknowledgement",
"AP": "Accepted",
"RE": "Rejected",

} as const;

/**
 * Keys of {@link applicationResponseTypeCodes}.
 */
export type applicationResponseTypeCodesKey = "AB" | "AP" | "RE";
export const applicationResponseTypeCodesKeys = [
  "AB",
  "AP",
  "RE",
] as const satisfies readonly [applicationResponseTypeCodesKey, ...applicationResponseTypeCodesKey[]];
