// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @version D.17A
 *
 * @category Peppol Values
 *
 * @title Application Response type code (UNCL4343 Subset)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4343/
 */
export const applicationResponseTypeCodes = { AB: 'Message acknowledgement', AP: 'Accepted', RE: 'Rejected' } as const;

/**
 * @description Keys of {@link applicationResponseTypeCodes}.
 */
export type applicationResponseTypeCodesKey = 'AB' | 'AP' | 'RE';
export const applicationResponseTypeCodesKeys = ['AB', 'AP', 'RE'] as const satisfies readonly [
  applicationResponseTypeCodesKey,
  ...applicationResponseTypeCodesKey[],
];
