// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @version D.16B
 *
 * @category Peppol Values
 *
 * @title Charge reason code (UNCL7161)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL7161/
 */
export const chargeReasonCodes = {
  /**
   * @description The service of providing advertising.
   */
  AA: 'Advertising',
  /**
   * @description The service of providing telecommunication activities and/or faclities.
   */
  AAA: 'Telecommunication',
  /**
   * @description The service of making technical modifications to a product.
   */
  AAC: 'Technical modification',
  /**
   * @description The service of producing to order.
   */
  AAD: 'Job-order production',
  /**
   * @description The service of providing money for outlays on behalf of a trading partner.
   */
  AAE: 'Outlays',
  /**
   * @description The service of providing services outside the premises of the provider.
   */
  AAF: 'Off-premises',
  /**
   * @description The service of providing additional processing.
   */
  AAH: 'Additional processing',
  /**
   * @description The service of certifying validity.
   */
  AAI: 'Attesting',
  /**
   * @description The service of accepting goods or services.
   */
  AAS: 'Acceptance',
  /**
   * @description The service to provide a rush delivery.
   */
  AAT: 'Rush delivery',
  /**
   * @description The service of providing special construction.
   */
  AAV: 'Special construction',
  /**
   * @description The service of providing airport facilities.
   */
  AAY: 'Airport facilities',
  /**
   * @description The service allowing a party to use another party's facilities.
   */
  AAZ: 'Concession',
  /**
   * @description The service provided to hold a compulsory inventory.
   */
  ABA: 'Compulsory storage',
  /**
   * @description Remove or off-load fuel from vehicle, vessel or craft.
   */
  ABB: 'Fuel removal',
  /**
   * @description Service of delivering goods to an aircraft from local storage.
   */
  ABC: 'Into plane',
  /**
   * @description The service of providing labour beyond the established limit of working hours.
   */
  ABD: 'Overtime',
  /**
   * @description The service of providing specific tooling.
   */
  ABF: 'Tooling',
  /**
   * @description Miscellaneous services.
   */
  ABK: 'Miscellaneous',
  /**
   * @description The service of providing additional packaging.
   */
  ABL: 'Additional packaging',
  /**
   * @description The service of providing additional padding materials required to secure and protect a cargo within a shipping container.
   */
  ABN: 'Dunnage',
  /**
   * @description The service of packing items into a container.
   */
  ABR: 'Containerisation',
  /**
   * @description The service of packing items into a carton.
   */
  ABS: 'Carton packing',
  /**
   * @description The service of hessian wrapping.
   */
  ABT: 'Hessian wrapped',
  /**
   * @description The service of packing in polyethylene wrapping.
   */
  ABU: 'Polyethylene wrap packing',
  /**
   * @description Miscellaneous treatment service.
   */
  ACF: 'Miscellaneous treatment',
  /**
   * @description The service of providing enamelling treatment.
   */
  ACG: 'Enamelling treatment',
  /**
   * @description The service of treating with heat.
   */
  ACH: 'Heat treatment',
  /**
   * @description The service of providing plating treatment.
   */
  ACI: 'Plating treatment',
  /**
   * @description The service of painting.
   */
  ACJ: 'Painting',
  /**
   * @description The service of polishing.
   */
  ACK: 'Polishing',
  /**
   * @description The service of priming.
   */
  ACL: 'Priming',
  /**
   * @description The service of preservation treatment.
   */
  ACM: 'Preservation treatment',
  /**
   * @description Fitting service.
   */
  ACS: 'Fitting',
  /**
   * @description The service of consolidating multiple consignments into one shipment.
   */
  ADC: 'Consolidation',
  /**
   * @description The service of providing a bill of lading document.
   */
  ADE: 'Bill of lading',
  /**
   * @description The service of surrounding a product with an air bag.
   */
  ADJ: 'Airbag',
  /**
   * @description The service of transferring.
   */
  ADK: 'Transfer',
  /**
   * @description The service of securing a stack of products on a slipsheet.
   */
  ADL: 'Slipsheet',
  /**
   * @description Binding service.
   */
  ADM: 'Binding',
  /**
   * @description The service of repairing or replacing a broken returnable package.
   */
  ADN: 'Repair or replacement of broken returnable package',
  /**
   * @description A code indicating efficient logistics services.
   */
  ADO: 'Efficient logistics',
  /**
   * @description A code indicating that merchandising services are in operation.
   */
  ADP: 'Merchandising',
  /**
   * @description A code indicating that product mixing services are in operation.
   */
  ADQ: 'Product mix',
  /**
   * @description A code indicating that other non-specific services are in operation.
   */
  ADR: 'Other services',
  /**
   * @description The service of picking up or collection of goods.
   */
  ADT: 'Pick-up',
  /**
   * @description The special services provided due to chronic illness.
   */
  ADW: 'Chronic illness',
  /**
   * @description A service provided by a buyer when introducing a new product from a suppliers range to the range traded by the buyer.
   */
  ADY: 'New product introduction',
  /**
   * @description Direct delivery service.
   */
  ADZ: 'Direct delivery',
  /**
   * @description The service of diverting deliverables.
   */
  AEA: 'Diversion',
  /**
   * @description The service is a disconnection.
   */
  AEB: 'Disconnect',
  /**
   * @description Distribution service.
   */
  AEC: 'Distribution',
  /**
   * @description A service for handling hazardous cargo.
   */
  AED: 'Handling of hazardous cargo',
  /**
   * @description The service of renting and/or leasing.
   */
  AEF: 'Rents and leases',
  /**
   * @description Delivery to a different location than previously contracted.
   */
  AEH: 'Location differential',
  /**
   * @description Fuel being put into the aircraft.
   */
  AEI: 'Aircraft refueling',
  /**
   * @description Fuel being shipped into a storage system.
   */
  AEJ: 'Fuel shipped into storage',
  /**
   * @description The provision of a cash on delivery (COD) service.
   */
  AEK: 'Cash on delivery',
  /**
   * @description A service related to the processing of small orders.
   */
  AEL: 'Small order processing service',
  /**
   * @description The provision of clerical or administrative services.
   */
  AEM: 'Clerical or administrative services',
  /**
   * @description The service of providing a guarantee.
   */
  AEN: 'Guarantee',
  /**
   * @description The service of collection and recycling products.
   */
  AEO: 'Collection and recycling',
  /**
   * @description The service of collecting copyright fees.
   */
  AEP: 'Copyright fee collection',
  /**
   * @description The service of providing veterinary inspection.
   */
  AES: 'Veterinary inspection service',
  /**
   * @description Special service when the subject is a pensioner.
   */
  AET: 'Pensioner service',
  /**
   * @description Special service when the subject holds a medicine free pass.
   */
  AEU: 'Medicine free pass holder',
  /**
   * @description The provision of an environmental protection service.
   */
  AEV: 'Environmental protection service',
  /**
   * @description The provision of an environmental clean-up service.
   */
  AEW: 'Environmental clean-up service',
  /**
   * @description Service of processing a national cheque outside the ordering customer's bank trading area.
   */
  AEX: 'National cheque processing service outside account area',
  /**
   * @description Service of processing a national payment to a beneficiary holding an account outside the trading area of the ordering customer's bank.
   */
  AEY: 'National payment service outside account area',
  /**
   * @description Service of processing a national payment to a beneficiary holding an account within the trading area of the ordering customer's bank.
   */
  AEZ: 'National payment service within account area',
  /**
   * @description The service of making adjustments.
   */
  AJ: 'Adjustments',
  /**
   * @description The service of authenticating.
   */
  AU: 'Authentication',
  /**
   * @description The provision of cataloguing services.
   */
  CA: 'Cataloguing',
  /**
   * @description Movement of goods by heavy duty cart or vehicle.
   */
  CAB: 'Cartage',
  /**
   * @description The service of certifying.
   */
  CAD: 'Certification',
  /**
   * @description The service of providing a certificate of conformance.
   */
  CAE: 'Certificate of conformance',
  /**
   * @description The service of providing a certificate of origin.
   */
  CAF: 'Certificate of origin',
  /**
   * @description The service of cutting.
   */
  CAI: 'Cutting',
  /**
   * @description The service provided by consulates.
   */
  CAJ: 'Consular service',
  /**
   * @description The service of collecting goods by the customer.
   */
  CAK: 'Customer collection',
  /**
   * @description Provision of a payroll payment service.
   */
  CAL: 'Payroll payment service',
  /**
   * @description Provision of a cash transportation service.
   */
  CAM: 'Cash transportation',
  /**
   * @description Provision of a home banking service.
   */
  CAN: 'Home banking service',
  /**
   * @description Provision of a service as specified in a bilateral special agreement.
   */
  CAO: 'Bilateral agreement service',
  /**
   * @description Provision of an insurance brokerage service.
   */
  CAP: 'Insurance brokerage service',
  /**
   * @description Provision of a cheque generation service.
   */
  CAQ: 'Cheque generation',
  /**
   * @description Service of assigning a preferential location for merchandising.
   */
  CAR: 'Preferential merchandising location',
  /**
   * @description The service of providing a crane.
   */
  CAS: 'Crane',
  /**
   * @description Providing a colour which is different from the default colour.
   */
  CAT: 'Special colour service',
  /**
   * @description The provision of sorting services.
   */
  CAU: 'Sorting',
  /**
   * @description The service of collecting and recycling batteries.
   */
  CAV: 'Battery collection and recycling',
  /**
   * @description The fee the consumer must pay the manufacturer to take back the product.
   */
  CAW: 'Product take back fee',
  /**
   * @description Informs the stockholder it is free to distribute the quality controlled passed goods.
   */
  CAX: 'Quality control released',
  /**
   * @description Instructs the stockholder to withhold distribution of the goods until the manufacturer has completed a quality control assessment.
   */
  CAY: 'Quality control held',
  /**
   * @description Instructs the stockholder to withhold distribution of goods which have failed quality control tests.
   */
  CAZ: 'Quality control embargo',
  /**
   * @description Car loading service.
   */
  CD: 'Car loading',
  /**
   * @description Cleaning service.
   */
  CG: 'Cleaning',
  /**
   * @description The service of providing cigarette stamping.
   */
  CS: 'Cigarette stamping',
  /**
   * @description The service of doing a count and recount.
   */
  CT: 'Count and recount',
  /**
   * @description The service of providing layout/design.
   */
  DAB: 'Layout/design',
  /**
   * @description Allowance given when a specific part of a suppliers assortment is purchased by the buyer.
   */
  DAC: 'Assortment allowance',
  /**
   * @description The service of unloading by the driver.
   */
  DAD: 'Driver assigned unloading',
  /**
   * @description A special allowance or charge applicable to a specific debtor.
   */
  DAF: 'Debtor bound',
  /**
   * @description An allowance offered by a party dealing a certain brand or brands of products.
   */
  DAG: 'Dealer allowance',
  /**
   * @description An allowance given by the manufacturer which should be transfered to the consumer.
   */
  DAH: 'Allowance transferable to the consumer',
  /**
   * @description An allowance or charge related to the growth of business over a pre-determined period of time.
   */
  DAI: 'Growth of business',
  /**
   * @description An allowance related to the introduction of a new product to the range of products traded by a retailer.
   */
  DAJ: 'Introduction allowance',
  /**
   * @description A code indicating special conditions related to a multi-buy promotion.
   */
  DAK: 'Multi-buy promotion',
  /**
   * @description An allowance or charge related to the establishment and on-going maintenance of a partnership.
   */
  DAL: 'Partnership',
  /**
   * @description An allowance or change related to the handling of returns.
   */
  DAM: 'Return handling',
  /**
   * @description Charge levied because the minimum order quantity could not be fulfilled.
   */
  DAN: 'Minimum order not fulfilled charge',
  /**
   * @description Allowance for reaching or exceeding an agreed sales threshold at the point of sales.
   */
  DAO: 'Point of sales threshold allowance',
  /**
   * @description A special discount related to the purchase of products through a wholesaler.
   */
  DAP: 'Wholesaling discount',
  /**
   * @description Fee for the transfer of transferable documentary credits.
   */
  DAQ: 'Documentary credits transfer commission',
  /**
   * @description The service of providing delivery.
   */
  DL: 'Delivery',
  /**
   * @description The service of providing engraving.
   */
  EG: 'Engraving',
  /**
   * @description The service of expediting.
   */
  EP: 'Expediting',
  /**
   * @description The service of guaranteeing exchange rate.
   */
  ER: 'Exchange rate guarantee',
  /**
   * @description The service of providing fabrication.
   */
  FAA: 'Fabrication',
  /**
   * @description The service of load balancing.
   */
  FAB: 'Freight equalization',
  /**
   * @description The service of providing freight's extraordinary handling.
   */
  FAC: 'Freight extraordinary handling',
  /**
   * @description The service of moving goods, by whatever means, from one place to another.
   */
  FC: 'Freight service',
  /**
   * @description The service of providing filling/handling.
   */
  FH: 'Filling/handling',
  /**
   * @description The service of providing financing.
   */
  FI: 'Financing',
  /**
   * @description The service of grinding.
   */
  GAA: 'Grinding',
  /**
   * @description The service of providing a hose.
   */
  HAA: 'Hose',
  /**
   * @description Handling service.
   */
  HD: 'Handling',
  /**
   * @description The service of hoisting and hauling.
   */
  HH: 'Hoisting and hauling',
  /**
   * @description The service of installing.
   */
  IAA: 'Installation',
  /**
   * @description The service of installing and providing warranty.
   */
  IAB: 'Installation and warranty',
  /**
   * @description The service of providing delivery inside.
   */
  ID: 'Inside delivery',
  /**
   * @description The service of inspection.
   */
  IF: 'Inspection',
  /**
   * @description The service of providing installation and training.
   */
  IR: 'Installation and training',
  /**
   * @description The service of providing an invoice.
   */
  IS: 'Invoicing',
  /**
   * @description The service of preparing food in accordance with Jewish law.
   */
  KO: 'Koshering',
  /**
   * @description The service of counting by the carrier.
   */
  L1: 'Carrier count',
  /**
   * @description Labelling service.
   */
  LA: 'Labelling',
  /**
   * @description The service to provide required labour.
   */
  LAA: 'Labour',
  /**
   * @description The service of repairing and returning.
   */
  LAB: 'Repair and return',
  /**
   * @description The service of legalising.
   */
  LF: 'Legalisation',
  /**
   * @description The service of mounting.
   */
  MAE: 'Mounting',
  /**
   * @description The service of mailing an invoice.
   */
  MI: 'Mail invoice',
  /**
   * @description The service of mailing an invoice to each location.
   */
  ML: 'Mail invoice to each location',
  /**
   * @description The service of providing non-returnable containers.
   */
  NAA: 'Non-returnable containers',
  /**
   * @description The service of providing outside cable connectors.
   */
  OA: 'Outside cable connectors',
  /**
   * @description The service of including the invoice with the shipment.
   */
  PA: 'Invoice with shipment',
  /**
   * @description The service of phosphatizing the steel.
   */
  PAA: 'Phosphatizing (steel treatment)',
  /**
   * @description The service of packing.
   */
  PC: 'Packing',
  /**
   * @description The service of palletizing.
   */
  PL: 'Palletizing',
  /**
   * @description Price variation related to energy and or raw materials cost variation.
   */
  PRV: 'Price variation',
  /**
   * @description The service of repacking.
   */
  RAB: 'Repacking',
  /**
   * @description The service of repairing.
   */
  RAC: 'Repair',
  /**
   * @description The service of providing returnable containers.
   */
  RAD: 'Returnable container',
  /**
   * @description The service of restocking.
   */
  RAF: 'Restocking',
  /**
   * @description The service of re-delivering.
   */
  RE: 'Re-delivery',
  /**
   * @description The service of refurbishing.
   */
  RF: 'Refurbishing',
  /**
   * @description The service of providing rail wagons for hire.
   */
  RH: 'Rail wagon hire',
  /**
   * @description The service of loading goods.
   */
  RV: 'Loading',
  /**
   * @description The service of salvaging.
   */
  SA: 'Salvaging',
  /**
   * @description The service of shipping and handling.
   */
  SAA: 'Shipping and handling',
  /**
   * @description The service of special packaging.
   */
  SAD: 'Special packaging',
  /**
   * @description The service of stamping.
   */
  SAE: 'Stamping',
  /**
   * @description The service of unloading by the consignee.
   */
  SAI: 'Consignee unload',
  /**
   * @description The service of shrink-wrapping.
   */
  SG: 'Shrink-wrap',
  /**
   * @description The service of special handling.
   */
  SH: 'Special handling',
  /**
   * @description The service of providing a special finish.
   */
  SM: 'Special finish',
  /**
   * @description The service of setting-up.
   */
  SU: 'Set-up',
  /**
   * @description The service of providing tanks for hire.
   */
  TAB: 'Tank renting',
  /**
   * @description The service of testing.
   */
  TAC: 'Testing',
  /**
   * @description The service of providing third party billing for transportation.
   */
  TT: 'Transportation - third party billing',
  /**
   * @description The service of providing transportation by the vendor.
   */
  TV: 'Transportation by vendor',
  /**
   * @description The service of delivering goods at the yard.
   */
  V1: 'Drop yard',
  /**
   * @description The service of delivering goods at the dock.
   */
  V2: 'Drop dock',
  /**
   * @description The service of storing and handling of goods in a warehouse.
   */
  WH: 'Warehousing',
  /**
   * @description The service of combining all shipments for the same day.
   */
  XAA: 'Combine all same day shipment',
  /**
   * @description The service of providing split pick-up.
   */
  YY: 'Split pick-up',
  /**
   * @description A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to
   * the code list.
   */
  ZZZ: 'Mutually defined',
} as const;

/**
 * @description Keys of {@link chargeReasonCodes}.
 */
export type chargeReasonCodesKey =
  | 'AA'
  | 'AAA'
  | 'AAC'
  | 'AAD'
  | 'AAE'
  | 'AAF'
  | 'AAH'
  | 'AAI'
  | 'AAS'
  | 'AAT'
  | 'AAV'
  | 'AAY'
  | 'AAZ'
  | 'ABA'
  | 'ABB'
  | 'ABC'
  | 'ABD'
  | 'ABF'
  | 'ABK'
  | 'ABL'
  | 'ABN'
  | 'ABR'
  | 'ABS'
  | 'ABT'
  | 'ABU'
  | 'ACF'
  | 'ACG'
  | 'ACH'
  | 'ACI'
  | 'ACJ'
  | 'ACK'
  | 'ACL'
  | 'ACM'
  | 'ACS'
  | 'ADC'
  | 'ADE'
  | 'ADJ'
  | 'ADK'
  | 'ADL'
  | 'ADM'
  | 'ADN'
  | 'ADO'
  | 'ADP'
  | 'ADQ'
  | 'ADR'
  | 'ADT'
  | 'ADW'
  | 'ADY'
  | 'ADZ'
  | 'AEA'
  | 'AEB'
  | 'AEC'
  | 'AED'
  | 'AEF'
  | 'AEH'
  | 'AEI'
  | 'AEJ'
  | 'AEK'
  | 'AEL'
  | 'AEM'
  | 'AEN'
  | 'AEO'
  | 'AEP'
  | 'AES'
  | 'AET'
  | 'AEU'
  | 'AEV'
  | 'AEW'
  | 'AEX'
  | 'AEY'
  | 'AEZ'
  | 'AJ'
  | 'AU'
  | 'CA'
  | 'CAB'
  | 'CAD'
  | 'CAE'
  | 'CAF'
  | 'CAI'
  | 'CAJ'
  | 'CAK'
  | 'CAL'
  | 'CAM'
  | 'CAN'
  | 'CAO'
  | 'CAP'
  | 'CAQ'
  | 'CAR'
  | 'CAS'
  | 'CAT'
  | 'CAU'
  | 'CAV'
  | 'CAW'
  | 'CAX'
  | 'CAY'
  | 'CAZ'
  | 'CD'
  | 'CG'
  | 'CS'
  | 'CT'
  | 'DAB'
  | 'DAC'
  | 'DAD'
  | 'DAF'
  | 'DAG'
  | 'DAH'
  | 'DAI'
  | 'DAJ'
  | 'DAK'
  | 'DAL'
  | 'DAM'
  | 'DAN'
  | 'DAO'
  | 'DAP'
  | 'DAQ'
  | 'DL'
  | 'EG'
  | 'EP'
  | 'ER'
  | 'FAA'
  | 'FAB'
  | 'FAC'
  | 'FC'
  | 'FH'
  | 'FI'
  | 'GAA'
  | 'HAA'
  | 'HD'
  | 'HH'
  | 'IAA'
  | 'IAB'
  | 'ID'
  | 'IF'
  | 'IR'
  | 'IS'
  | 'KO'
  | 'L1'
  | 'LA'
  | 'LAA'
  | 'LAB'
  | 'LF'
  | 'MAE'
  | 'MI'
  | 'ML'
  | 'NAA'
  | 'OA'
  | 'PA'
  | 'PAA'
  | 'PC'
  | 'PL'
  | 'PRV'
  | 'RAB'
  | 'RAC'
  | 'RAD'
  | 'RAF'
  | 'RE'
  | 'RF'
  | 'RH'
  | 'RV'
  | 'SA'
  | 'SAA'
  | 'SAD'
  | 'SAE'
  | 'SAI'
  | 'SG'
  | 'SH'
  | 'SM'
  | 'SU'
  | 'TAB'
  | 'TAC'
  | 'TT'
  | 'TV'
  | 'V1'
  | 'V2'
  | 'WH'
  | 'XAA'
  | 'YY'
  | 'ZZZ';
export const chargeReasonCodesKeys = [
  'AA',
  'AAA',
  'AAC',
  'AAD',
  'AAE',
  'AAF',
  'AAH',
  'AAI',
  'AAS',
  'AAT',
  'AAV',
  'AAY',
  'AAZ',
  'ABA',
  'ABB',
  'ABC',
  'ABD',
  'ABF',
  'ABK',
  'ABL',
  'ABN',
  'ABR',
  'ABS',
  'ABT',
  'ABU',
  'ACF',
  'ACG',
  'ACH',
  'ACI',
  'ACJ',
  'ACK',
  'ACL',
  'ACM',
  'ACS',
  'ADC',
  'ADE',
  'ADJ',
  'ADK',
  'ADL',
  'ADM',
  'ADN',
  'ADO',
  'ADP',
  'ADQ',
  'ADR',
  'ADT',
  'ADW',
  'ADY',
  'ADZ',
  'AEA',
  'AEB',
  'AEC',
  'AED',
  'AEF',
  'AEH',
  'AEI',
  'AEJ',
  'AEK',
  'AEL',
  'AEM',
  'AEN',
  'AEO',
  'AEP',
  'AES',
  'AET',
  'AEU',
  'AEV',
  'AEW',
  'AEX',
  'AEY',
  'AEZ',
  'AJ',
  'AU',
  'CA',
  'CAB',
  'CAD',
  'CAE',
  'CAF',
  'CAI',
  'CAJ',
  'CAK',
  'CAL',
  'CAM',
  'CAN',
  'CAO',
  'CAP',
  'CAQ',
  'CAR',
  'CAS',
  'CAT',
  'CAU',
  'CAV',
  'CAW',
  'CAX',
  'CAY',
  'CAZ',
  'CD',
  'CG',
  'CS',
  'CT',
  'DAB',
  'DAC',
  'DAD',
  'DAF',
  'DAG',
  'DAH',
  'DAI',
  'DAJ',
  'DAK',
  'DAL',
  'DAM',
  'DAN',
  'DAO',
  'DAP',
  'DAQ',
  'DL',
  'EG',
  'EP',
  'ER',
  'FAA',
  'FAB',
  'FAC',
  'FC',
  'FH',
  'FI',
  'GAA',
  'HAA',
  'HD',
  'HH',
  'IAA',
  'IAB',
  'ID',
  'IF',
  'IR',
  'IS',
  'KO',
  'L1',
  'LA',
  'LAA',
  'LAB',
  'LF',
  'MAE',
  'MI',
  'ML',
  'NAA',
  'OA',
  'PA',
  'PAA',
  'PC',
  'PL',
  'PRV',
  'RAB',
  'RAC',
  'RAD',
  'RAF',
  'RE',
  'RF',
  'RH',
  'RV',
  'SA',
  'SAA',
  'SAD',
  'SAE',
  'SAI',
  'SG',
  'SH',
  'SM',
  'SU',
  'TAB',
  'TAC',
  'TT',
  'TV',
  'V1',
  'V2',
  'WH',
  'XAA',
  'YY',
  'ZZZ',
] as const satisfies readonly [chargeReasonCodesKey, ...Array<chargeReasonCodesKey>];
