// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @version D.16B
 *
 * @category Peppol Values
 *
 * @title Credit note type code (UNCL1001 subset)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-cn/
 */
export const creditNoteTypeCodes = {
  /**
   * @description Document message used to provide credit information related to a transaction for goods or services to the relevant party.
   */
  '81': 'Credit note related to goods or services',
  /**
   * @description Document message for providing credit information related to financial adjustments to the relevant party, e.g., bonuses.
   */
  '83': 'Credit note related to financial adjustments',
  /**
   * @description (1113) Document/message for providing credit information to the relevant party.
   */
  '381': 'Credit note',
  /**
   * @description Credit note related to assigned invoice(s).
   */
  '396': 'Factored credit note',
  /**
   * @description Document/message for providing credit information to the relevant party.
   */
  '532': "Forwarder's credit note",
};

/**
 * @description Keys of {@link creditNoteTypeCodes}.
 */
export type CreditNoteTypeCodesKeys = 81 | 83 | 381 | 396 | 532;

/**
 * @description Keys of {@link creditNoteTypeCodes}.
 */
export const creditNoteTypeCodesKeys = [81, 83, 381, 396, 532] as const;
