// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Credit note type code (UNCL1001 subset)
 * @version D.16B
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-cn/
 * @enum
 * @category Peppol Values
 */
export const creditNoteTypeCodes = {
/**
* Document message used to provide credit information related to a transaction for goods or services to the relevant party.
*/
"81": "Credit note related to goods or services",
/**
* Document message for providing credit information related to financial adjustments to the relevant party, e.g., bonuses.
*/
"83": "Credit note related to financial adjustments",
/**
* (1113) Document/message for providing credit information to the relevant party.
*/
"381": "Credit note",
/**
* Credit note related to assigned invoice(s).
*/
"396": "Factored credit note",
/**
* Document/message for providing credit information to the relevant party.
*/
"532": "Forwarder's credit note",

} as const;

/**
 * Keys of {@link creditNoteTypeCodes}.
 */
export type creditNoteTypeCodesKey = "81" | "83" | "381" | "396" | "532";
export const creditNoteTypeCodesKeys = [
  "81",
  "83",
  "381",
  "396",
  "532",
] as const satisfies readonly [creditNoteTypeCodesKey, ...creditNoteTypeCodesKey[]];
