// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @version 2018-01-01
 *
 * @category Peppol Values
 *
 * @title ISO 4217 Currency codes
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/ISO4217/
 */
export const currencyCodes = {
  AED: 'UAE Dirham',
  AFN: 'Afghani',
  ALL: 'Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijan Manat',
  BAM: 'Convertible Mark',
  BBD: 'Barbados Dollar',
  BDT: 'Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundi Franc',
  BMD: 'Bermudian Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Boliviano',
  BOV: 'Mvdol',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTN: 'Ngultrum',
  BWP: 'Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHE: 'WIR Euro',
  CHF: 'Swiss Franc',
  CHW: 'WIR Franc',
  CLF: 'Unidad de Fomento',
  CLP: 'Chilean Peso',
  CNY: 'Yuan Renminbi',
  COP: 'Colombian Peso',
  COU: 'Unidad de Valor Real',
  CRC: 'Costa Rican Colon',
  CUP: 'Cuban Peso',
  CVE: 'Cabo Verde Escudo',
  CZK: 'Czech Koruna',
  DJF: 'Djibouti Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fiji Dollar',
  FKP: 'Falkland Islands Pound',
  GBP: 'Pound Sterling',
  GEL: 'Lari',
  GHS: 'Ghana Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Quetzal',
  GYD: 'Guyana Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Lempira',
  HTG: 'Gourde',
  HUF: 'Forint',
  IDR: 'Rupiah',
  ILS: 'New Israeli Sheqel',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Iceland Krona',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Som',
  KHR: 'Riel',
  KMF: 'Comorian Franc',
  KPW: 'North Korean Won',
  KRW: 'Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Tenge',
  LAK: 'Lao Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lanka Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Loti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Denar',
  MMK: 'Kyat',
  MNT: 'Tugrik',
  MOP: 'Pataca',
  MRU: 'Ouguiya',
  MUR: 'Mauritius Rupee',
  MVR: 'Rufiyaa',
  MWK: 'Malawi Kwacha',
  MXN: 'Mexican Peso',
  MXV: 'Mexican Unidad de Inversion (UDI)',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambique Metical',
  NAD: 'Namibia Dollar',
  NGN: 'Naira',
  NIO: 'Cordoba Oro',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Rial Omani',
  PAB: 'Balboa',
  PEN: 'Sol',
  PGK: 'Kina',
  PHP: 'Philippine Piso',
  PKR: 'Pakistan Rupee',
  PLN: 'Zloty',
  PYG: 'Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwanda Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychelles Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLE: 'Sierra Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinam Dollar',
  SSP: 'South Sudanese Pound',
  STN: 'Dobra',
  SVC: 'El Salvador Colon',
  SYP: 'Syrian Pound',
  SZL: 'Lilangeni',
  THB: 'Baht',
  TJS: 'Somoni',
  TMT: 'Turkmenistan New Manat',
  TND: 'Tunisian Dinar',
  TOP: 'Pa’anga',
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Hryvnia',
  UGX: 'Uganda Shilling',
  USD: 'US Dollar',
  USN: 'US Dollar (Next day)',
  UYI: 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
  UYU: 'Peso Uruguayo',
  UYW: 'Unidad Previsional',
  UZS: 'Uzbekistan Sum',
  VED: 'Bolívar Soberano, new valuation',
  VES: 'Bolívar Soberano',
  VND: 'Dong',
  VUV: 'Vatu',
  WST: 'Tala',
  XAF: 'CFA Franc BEAC',
  XAG: 'Silver',
  XAU: 'Gold',
  XBA: 'Bond Markets Unit European Composite Unit (EURCO)',
  XBB: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
  XBC: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
  XBD: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
  XCD: 'East Caribbean Dollar',
  XDR: 'SDR (Special Drawing Right)',
  XOF: 'CFA Franc BCEAO',
  XPD: 'Palladium',
  XPF: 'CFP Franc',
  XPT: 'Platinum',
  XSU: 'Sucre',
  XTS: 'Codes specifically reserved for testing purposes',
  XUA: 'ADB Unit of Account',
  YER: 'Yemeni Rial',
  ZAR: 'Rand',
  ZMW: 'Zambian Kwacha',
  ZWG: 'Zimbabwe Gold',
  XXX: 'The codes assigned for transactions where no currency is involved',
  CNH: 'Renminbi (offshore)',
} as const;

/**
 * @description Keys of {@link currencyCodes}.
 */
export type currencyCodesKey =
  | 'AED'
  | 'AFN'
  | 'ALL'
  | 'AMD'
  | 'ANG'
  | 'AOA'
  | 'ARS'
  | 'AUD'
  | 'AWG'
  | 'AZN'
  | 'BAM'
  | 'BBD'
  | 'BDT'
  | 'BGN'
  | 'BHD'
  | 'BIF'
  | 'BMD'
  | 'BND'
  | 'BOB'
  | 'BOV'
  | 'BRL'
  | 'BSD'
  | 'BTN'
  | 'BWP'
  | 'BYN'
  | 'BZD'
  | 'CAD'
  | 'CDF'
  | 'CHE'
  | 'CHF'
  | 'CHW'
  | 'CLF'
  | 'CLP'
  | 'CNY'
  | 'COP'
  | 'COU'
  | 'CRC'
  | 'CUP'
  | 'CVE'
  | 'CZK'
  | 'DJF'
  | 'DKK'
  | 'DOP'
  | 'DZD'
  | 'EGP'
  | 'ERN'
  | 'ETB'
  | 'EUR'
  | 'FJD'
  | 'FKP'
  | 'GBP'
  | 'GEL'
  | 'GHS'
  | 'GIP'
  | 'GMD'
  | 'GNF'
  | 'GTQ'
  | 'GYD'
  | 'HKD'
  | 'HNL'
  | 'HTG'
  | 'HUF'
  | 'IDR'
  | 'ILS'
  | 'INR'
  | 'IQD'
  | 'IRR'
  | 'ISK'
  | 'JMD'
  | 'JOD'
  | 'JPY'
  | 'KES'
  | 'KGS'
  | 'KHR'
  | 'KMF'
  | 'KPW'
  | 'KRW'
  | 'KWD'
  | 'KYD'
  | 'KZT'
  | 'LAK'
  | 'LBP'
  | 'LKR'
  | 'LRD'
  | 'LSL'
  | 'LYD'
  | 'MAD'
  | 'MDL'
  | 'MGA'
  | 'MKD'
  | 'MMK'
  | 'MNT'
  | 'MOP'
  | 'MRU'
  | 'MUR'
  | 'MVR'
  | 'MWK'
  | 'MXN'
  | 'MXV'
  | 'MYR'
  | 'MZN'
  | 'NAD'
  | 'NGN'
  | 'NIO'
  | 'NOK'
  | 'NPR'
  | 'NZD'
  | 'OMR'
  | 'PAB'
  | 'PEN'
  | 'PGK'
  | 'PHP'
  | 'PKR'
  | 'PLN'
  | 'PYG'
  | 'QAR'
  | 'RON'
  | 'RSD'
  | 'RUB'
  | 'RWF'
  | 'SAR'
  | 'SBD'
  | 'SCR'
  | 'SDG'
  | 'SEK'
  | 'SGD'
  | 'SHP'
  | 'SLE'
  | 'SOS'
  | 'SRD'
  | 'SSP'
  | 'STN'
  | 'SVC'
  | 'SYP'
  | 'SZL'
  | 'THB'
  | 'TJS'
  | 'TMT'
  | 'TND'
  | 'TOP'
  | 'TRY'
  | 'TTD'
  | 'TWD'
  | 'TZS'
  | 'UAH'
  | 'UGX'
  | 'USD'
  | 'USN'
  | 'UYI'
  | 'UYU'
  | 'UYW'
  | 'UZS'
  | 'VED'
  | 'VES'
  | 'VND'
  | 'VUV'
  | 'WST'
  | 'XAF'
  | 'XAG'
  | 'XAU'
  | 'XBA'
  | 'XBB'
  | 'XBC'
  | 'XBD'
  | 'XCD'
  | 'XDR'
  | 'XOF'
  | 'XPD'
  | 'XPF'
  | 'XPT'
  | 'XSU'
  | 'XTS'
  | 'XUA'
  | 'YER'
  | 'ZAR'
  | 'ZMW'
  | 'ZWG'
  | 'XXX'
  | 'CNH';
export const currencyCodesKeys = [
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BOV',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHE',
  'CHF',
  'CHW',
  'CLF',
  'CLP',
  'CNY',
  'COP',
  'COU',
  'CRC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'GBP',
  'GEL',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IQD',
  'IRR',
  'ISK',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MXV',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLE',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SVC',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'USN',
  'UYI',
  'UYU',
  'UYW',
  'UZS',
  'VED',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XAG',
  'XAU',
  'XBA',
  'XBB',
  'XBC',
  'XBD',
  'XCD',
  'XDR',
  'XOF',
  'XPD',
  'XPF',
  'XPT',
  'XSU',
  'XTS',
  'XUA',
  'YER',
  'ZAR',
  'ZMW',
  'ZWG',
  'XXX',
  'CNH',
] as const satisfies readonly [currencyCodesKey, ...currencyCodesKey[]];
