// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Duty or tax or fee category code (Subset of UNCL5305)
 * @version D.16B
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/
 * @enum
 * @category Peppol Values
 */
export const dutyTaxFeeCategories = {
/**
* Code specifying that the standard VAT rate is levied from the invoicee.
*/
"AE": "Vat Reverse Charge",
/**
* Code specifying that taxes are not applicable.
*/
"E": "Exempt from Tax",
/**
* Code specifying the standard rate.
*/
"S": "Standard rate",
/**
* Code specifying that the goods are at a zero rate.
*/
"Z": "Zero rated goods",
/**
* Code specifying that the item is free export and taxes are not charged.
*/
"G": "Free export item, VAT not charged",
/**
* Code specifying that taxes are not applicable to the services.
*/
"O": "Services outside scope of tax",
/**
* A tax category code indicating the item is VAT exempt due to an intra-community supply in the European Economic Area.
*/
"K": "VAT exempt for EEA intra-community supply of goods and services",
/**
* Impuesto General Indirecto Canario (IGIC) is an indirect tax levied on goods and services supplied in the Canary Islands (Spain) by traders and professionals, as well as on import of goods.
*/
"L": "Canary Islands general indirect tax",
/**
* Impuesto sobre la Producción, los Servicios y la Importación (IPSI) is an indirect municipal tax, levied on the production, processing and import of all kinds of movable tangible property, the supply of services and the transfer of immovable property located in the cities of Ceuta and Melilla.
*/
"M": "Tax for production, services and importation in Ceuta and Melilla",
/**
* VAT not to be paid to the issuer of the invoice but directly to relevant tax authority. This code 		is allowed in the EN 16931 for Italy only based on the Italian A-deviation.
*/
"B": "Transferred (VAT), In Italy",

} as const;

/**
 * Keys of {@link dutyTaxFeeCategories}.
 */
export type dutyTaxFeeCategoriesKey = "AE" | "E" | "S" | "Z" | "G" | "O" | "K" | "L" | "M" | "B";
export const dutyTaxFeeCategoriesKeys = [
  "AE",
  "E",
  "S",
  "Z",
  "G",
  "O",
  "K",
  "L",
  "M",
  "B",
] as const satisfies readonly [dutyTaxFeeCategoriesKey, ...dutyTaxFeeCategoriesKey[]];
