// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @category Peppol Values
 *
 * @title Electronic Address Scheme (EAS)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/eas/
 */
export const electronicAddressCodes = {
  '2': 'System Information et Repertoire des Entreprise et des Etablissements: SIRENE',

  '7': 'Organisationsnummer (Swedish legal entities)',

  '9': 'SIRET-CODE',

  '37': 'LY-tunnus',

  '60': 'Data Universal Numbering System (D-U-N-S Number)',

  '88': 'EAN Location Code',

  '96': 'DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)',

  '97': 'FTI - Ediforum Italia, (EDIRA compliant)',

  '106':
    '"Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)"',

  '130': 'Directorates of the European Commission',

  '135': 'SIA Object Identifiers',

  '142': 'SECETI Object Identifiers',

  '151': 'Australian Business Number (ABN) Scheme',

  '177': 'Odette International Limited',

  '183': "Numéro d'identification suisse des enterprises (IDE), Swiss Unique Business Identification Number (UIDB)",

  '184': 'DIGSTORG',

  '188': 'Corporate Number of The Social Security and Tax Number System',

  '190': "Dutch Originator's Identification Number",

  '191': 'Centre of Registers and Information Systems of the Ministry of Justice',

  '192': 'Enhetsregisteret ved Bronnoysundregisterne',

  '193': 'UBL.BE party identifier',

  '195': 'Singapore UEN identifier',

  '196': 'Kennitala - Iceland legal id for individuals and legal entities',

  '198': 'ERSTORG',

  '199': 'Legal Entity Identifier (LEI)',

  '200': 'Legal entity code (Lithuania)',

  '201': 'Codice Univoco Unità Organizzativa iPA',

  '202': 'Indirizzo di Posta Elettronica Certificata',

  '204': 'Leitweg-ID',

  '208': "Numero d'entreprise / ondernemingsnummer / Unternehmensnummer",

  '209': 'GS1 identification keys',

  '210': 'CODICE FISCALE',

  '211': 'PARTITA IVA',

  '212': 'Finnish Organization Identifier',

  '213': 'Finnish Organization Value Add Tax Identifier',

  '215': 'Net service ID',

  '216': 'OVTcode',

  '218': 'Unified registration number (Latvia)',

  '221': 'The registered number of the qualified invoice issuer (Japan)',

  '230': 'National e-Invoicing Framework (Malaysia)',

  '235': 'UAE Tax Identification Number (TIN)',

  '9910': 'Hungary VAT number',

  '9913': 'Business Registers Network',

  '9914': 'Österreichische Umsatzsteuer-Identifikationsnummer',

  '9915': '"Österreichisches Verwaltungs bzw. Organisationskennzeichen"',

  '9918': '"SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T"',

  '9919': 'Kennziffer des Unternehmensregisters',

  '9920': 'Agencia Española de Administración Tributaria',

  '9922': 'Andorra VAT number',

  '9923': 'Albania VAT number',

  '9924': 'Bosnia and Herzegovina VAT number',

  '9925': 'Belgium VAT number',

  '9926': 'Bulgaria VAT number',

  '9927': 'Switzerland VAT number',

  '9928': 'Cyprus VAT number',

  '9929': 'Czech Republic VAT number',

  '9930': 'Germany VAT number',

  '9931': 'Estonia VAT number',

  '9932': 'United Kingdom VAT number',

  '9933': 'Greece VAT number',

  '9934': 'Croatia VAT number',

  '9935': 'Ireland VAT number',

  '9936': 'Liechtenstein VAT number',

  '9937': 'Lithuania VAT number',

  '9938': 'Luxemburg VAT number',

  '9939': 'Latvia VAT number',

  '9940': 'Monaco VAT number',

  '9941': 'Montenegro VAT number',

  '9942': 'Macedonia, the former Yugoslav Republic of VAT number',

  '9943': 'Malta VAT number',

  '9944': 'Netherlands VAT number',

  '9945': 'Poland VAT number',

  '9946': 'Portugal VAT number',

  '9947': 'Romania VAT number',

  '9948': 'Serbia VAT number',

  '9949': 'Slovenia VAT number',

  '9950': 'Slovakia VAT number',

  '9951': 'San Marino VAT number',

  '9952': 'Turkey VAT number',

  '9953': 'Holy See (Vatican City State) VAT number',

  '9957': 'French VAT number',

  '9959': 'Employer Identification Number (EIN, USA)',

  '147': 'Standard Company Code',

  '154': 'Identification number of economic subjects: (ICO)',

  '158': 'Identification number of economic subject (ICO) Act on State Statistics of 29 November 2001, § 27',

  '170': 'Teikoku Company Code',

  '194': 'KOIOS Open Technical Dictionary',

  '203': 'eDelivery Network Participant identifier',

  '205': 'CODDEST',

  '217': 'The Netherlands Chamber of Commerce and Industry establishment number',

  '225': 'FRCTC ELECTRONIC ADDRESS',

  '240': 'Register of legal persons (in French : Répertoire des personnes morales)',

  '244': 'Tax Identification (Tax ID), Nigeria',

  '245': 'Tax identification number (DIČ), Slovakia',
};

/**
 * @description Keys of {@link electronicAddressCodes}.
 */
export type ElectronicAddressCodesKeys =
  | 2
  | 7
  | 9
  | 37
  | 60
  | 88
  | 96
  | 97
  | 106
  | 130
  | 135
  | 142
  | 151
  | 177
  | 183
  | 184
  | 188
  | 190
  | 191
  | 192
  | 193
  | 195
  | 196
  | 198
  | 199
  | 200
  | 201
  | 202
  | 204
  | 208
  | 209
  | 210
  | 211
  | 212
  | 213
  | 215
  | 216
  | 218
  | 221
  | 230
  | 235
  | 9910
  | 9913
  | 9914
  | 9915
  | 9918
  | 9919
  | 9920
  | 9922
  | 9923
  | 9924
  | 9925
  | 9926
  | 9927
  | 9928
  | 9929
  | 9930
  | 9931
  | 9932
  | 9933
  | 9934
  | 9935
  | 9936
  | 9937
  | 9938
  | 9939
  | 9940
  | 9941
  | 9942
  | 9943
  | 9944
  | 9945
  | 9946
  | 9947
  | 9948
  | 9949
  | 9950
  | 9951
  | 9952
  | 9953
  | 9957
  | 9959
  | 147
  | 154
  | 158
  | 170
  | 194
  | 203
  | 205
  | 217
  | 225
  | 240
  | 244
  | 245;

/**
 * @description Keys of {@link electronicAddressCodes}.
 */
export const electronicAddressCodesKeys = [
  2, 7, 9, 37, 60, 88, 96, 97, 106, 130, 135, 142, 151, 177, 183, 184, 188, 190, 191, 192, 193, 195, 196, 198, 199, 200, 201, 202, 204, 208, 209, 210,
  211, 212, 213, 215, 216, 218, 221, 230, 235, 9910, 9913, 9914, 9915, 9918, 9919, 9920, 9922, 9923, 9924, 9925, 9926, 9927, 9928, 9929, 9930, 9931,
  9932, 9933, 9934, 9935, 9936, 9937, 9938, 9939, 9940, 9941, 9942, 9943, 9944, 9945, 9946, 9947, 9948, 9949, 9950, 9951, 9952, 9953, 9957, 9959, 147,
  154, 158, 170, 194, 203, 205, 217, 225, 240, 244, 245,
] as [string, ...string[]];
