// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Invoice status code (UNCL4343 Subset)
 * @version D.17A
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4343-T111/
 * @enum
 * @category Peppol Values
 */
export const invoiceStatusCodes = {
/**
* Indicates that an acknowledgement relating to receipt of message or transaction is required. Status is used when Buyer has received a readable invoice message that can be understood and submitted for processing by the Buyer.
*/
"AB": "Message acknowledgement",
/**
* Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) has been accepted. Status is used only when the Buyer has given a final approval of the invoice and the next step is payment
*/
"AP": "Accepted",
/**
* Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) is not accepted. Status is used only when the Buyer will not process the referenced Invoice any further. Buyer is rejecting this invoice but not necessarily the commercial transaction. Although it can be used also for rejection for commercial reasons (invoice not corresponding to delivery).
*/
"RE": "Rejected",
/**
* Indicates that the referenced message or transaction is being processed. Status is used when the processing of the Invoice has started in Buyers system.
*/
"IP": "In process",
/**
* Indicates that the processing of the referenced message has been halted pending response to a query. Status is used when Buyer will not proceed to accept the Invoice without receiving additional information from the Seller.
*/
"UQ": "Under query",
/**
* Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) has been accepted under conditions indicated in this message. Status is used when Buyer is accepting the Invoice under conditions stated in ‘Status Reason’ and proceed to pay accordingly unless disputed by Seller.
*/
"CA": "Conditionally accepted",
/**
* Indicates that the referenced document or transaction has been paid. Status is used only when the Buyer has initiated the payment of the invoice.
*/
"PD": "Paid",

} as const;

/**
 * Keys of {@link invoiceStatusCodes}.
 */
export type invoiceStatusCodesKey = "AB" | "AP" | "RE" | "IP" | "UQ" | "CA" | "PD";
export const invoiceStatusCodesKeys = [
  "AB",
  "AP",
  "RE",
  "IP",
  "UQ",
  "CA",
  "PD",
] as const satisfies readonly [invoiceStatusCodesKey, ...invoiceStatusCodesKey[]];
