// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @version D.16B
 *
 * @category Peppol Values
 *
 * @title Invoice type code (UNCL1001 subset)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-inv/
 */
export const invoiceTypeCodes = {
  /**
   * @description Document/message issued by a creditor to a debtor to request payment of one or more invoices past due.
   */
  '71': 'Request for payment',
  /**
   * @description Debit information related to a transaction for goods or services to the relevant party.
   */
  '80': 'Debit note related to goods or services',
  /**
   * @description Document/message claiming payment for the supply of metered services (e.g., gas, electricity, etc.) supplied to a fixed meter whose consumption
   * is measured over a period of time.
   */
  '82': 'Metered services invoice',
  /**
   * @description Document/message for providing debit information related to financial adjustments to the relevant party.
   */
  '84': 'Debit note related to financial adjustments',
  /**
   * @description Used to specify that the message is a tax notification.
   */
  '102': 'Tax notification',
  /**
   * @description The final payment request of a series of payment requests submitted upon completion of all the work.
   */
  '218': 'Final payment request based on completion of work',
  /**
   * @description A request for payment for completed units.
   */
  '219': 'Payment request for completed units',
  /**
   * @description Document/message specifying details of an incomplete invoice.
   */
  '326': 'Partial invoice',
  /**
   * @description Commercial transaction (invoice) will include a packing list.
   */
  '331': 'Commercial invoice which includes a packing list',
  /**
   * @description (1334) Document/message claiming payment for goods or services supplied under conditions agreed between seller and buyer.
   */
  '380': 'Commercial invoice',
  /**
   * @description Document/message in which a seller specifies the amount of commission, the percentage of the invoice amount, or some other basis for the
   * calculation of the commission to which a sales agent is entitled.
   */
  '382': 'Commission note',
  /**
   * @description Document/message for providing debit information to the relevant party.
   */
  '383': 'Debit note',
  /**
   * @description Commercial invoice that includes revised information differing from an earlier submission of the same invoice.
   */
  '384': 'Corrected invoice',
  /**
   * @description An invoice to pay amounts for goods and services in advance; these amounts will be subtracted from the final invoice.
   */
  '386': 'Prepayment invoice',
  /**
   * @description An invoice for tax purposes.
   */
  '388': 'Tax invoice',
  /**
   * @description An invoice the invoicee is producing instead of the seller.
   */
  '389': 'Self-billed invoice',
  /**
   * @description Invoice assigned to a third party for collection.
   */
  '393': 'Factored invoice',
  /**
   * @description Commercial invoice that covers a transaction other than one involving a sale.
   */
  '395': 'Consignment invoice',
  /**
   * @description Document/message reporting invoice discrepancies indentified by the forwarder.
   */
  '553': "Forwarder's invoice discrepancy report",
  /**
   * @description Document/message issued by an insurer specifying the cost of an insurance which has been effected and claiming payment therefore.
   */
  '575': "Insurer's invoice",
  /**
   * @description Invoice issued by a freight forwarder specifying services rendered and costs incurred and claiming payment therefore.
   */
  '623': "Forwarder's invoice",
  /**
   * @description Document/message issued by a transport operation specifying freight costs and charges incurred for a transport operation and stating conditions
   * of payment.
   */
  '780': 'Freight invoice',
  /**
   * @description Document notifying a claim.
   */
  '817': 'Claim notification',
  /**
   * @description Document/message to be prepared by an exporter in his country and presented to a diplomatic representation of the importing country for
   * endorsement and subsequently to be presented by the importer in connection with the import of the goods described therein.
   */
  '870': 'Consular invoice',
  /**
   * @description Partial invoice in the context of a specific construction project.
   */
  '875': 'Partial construction invoice',
  /**
   * @description Invoice concluding all previous partial construction invoices of a completed partial rendered service in the context of a specific construction
   * project.
   */
  '876': 'Partial final construction invoice',
  /**
   * @description Invoice concluding all previous partial invoices and partial final construction invoices in the context of a specific construction project.
   */
  '877': 'Final construction invoice',
};

/**
 * @description Keys of {@link invoiceTypeCodes}.
 */
export type InvoiceTypeCodesKeys =
  | 71
  | 80
  | 82
  | 84
  | 102
  | 218
  | 219
  | 326
  | 331
  | 380
  | 382
  | 383
  | 384
  | 386
  | 388
  | 389
  | 393
  | 395
  | 553
  | 575
  | 623
  | 780
  | 817
  | 870
  | 875
  | 876
  | 877;

/**
 * @description Keys of {@link invoiceTypeCodes}.
 */
export const invoiceTypeCodesKeys = [
  71, 80, 82, 84, 102, 218, 219, 326, 331, 380, 382, 383, 384, 386, 388, 389, 393, 395, 553, 575, 623, 780, 817, 870, 875, 876, 877,
] as [string, ...string[]];
