// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @version 1.0
 *
 * @category Peppol Values
 *
 * @title Mime code (subset of IANA code list)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/MimeCode/
 */
export const mimeCodes = {
  'text/csv': 'text/csv',

  'application/pdf': 'application/pdf',

  'image/png': 'image/png',

  'image/jpeg': 'image/jpeg',

  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',

  'application/vnd.oasis.opendocument.spreadsheet': 'application/vnd.oasis.opendocument.spreadsheet',
};

/**
 * @description Keys of {@link mimeCodes}.
 */
export type MimeCodesKeys =
  | 'text/csv'
  | 'application/pdf'
  | 'image/png'
  | 'image/jpeg'
  | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  | 'application/vnd.oasis.opendocument.spreadsheet';

/**
 * @description Keys of {@link mimeCodes}.
 */
export const mimeCodesKeys = [
  'text/csv',
  'application/pdf',
  'image/png',
  'image/jpeg',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.oasis.opendocument.spreadsheet',
] as const;
