// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Mime code (subset of IANA code list)
 * @version 1.0
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/MimeCode/
 * @enum
 * @category Peppol Values
 */
export const mimeCodes = {
"text/csv": "text/csv",
"application/pdf": "application/pdf",
"image/png": "image/png",
"image/jpeg": "image/jpeg",
"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
"application/vnd.oasis.opendocument.spreadsheet": "application/vnd.oasis.opendocument.spreadsheet",

} as const;

/**
 * Keys of {@link mimeCodes}.
 */
export type mimeCodesKey = "text/csv" | "application/pdf" | "image/png" | "image/jpeg" | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" | "application/vnd.oasis.opendocument.spreadsheet";
export const mimeCodesKeys = [
  "text/csv",
  "application/pdf",
  "image/png",
  "image/jpeg",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.oasis.opendocument.spreadsheet",
] as const satisfies readonly [mimeCodesKey, ...mimeCodesKey[]];
