// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Status Clarification Action (OpenPeppol)
 * @version 1.0
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/OPStatusAction/
 * @enum
 * @category Peppol Values
 */
export const opStatusAction = {
/**
* No action required
*/
"NOA": "No action required",
/**
* Missing information requested without re-issuing invoice
*/
"PIN": "Provide information",
/**
* Request to re-issue a corrected invoice
*/
"NIN": "Issue new invoice",
/**
* Request to fully cancel the referenced invoice with a credit note
*/
"CNF": "Credit fully",
/**
* Request to issue partial credit note for corrections only
*/
"CNP": "Credit partially",
/**
* Request to repay the amount paid on the invoice
*/
"CNA": "Credit the amount",
/**
* Requested action is not defined by code
*/
"OTH": "Other",

} as const;

/**
 * Keys of {@link opStatusAction}.
 */
export type opStatusActionKey = "NOA" | "PIN" | "NIN" | "CNF" | "CNP" | "CNA" | "OTH";
export const opStatusActionKeys = [
  "NOA",
  "PIN",
  "NIN",
  "CNF",
  "CNP",
  "CNA",
  "OTH",
] as const satisfies readonly [opStatusActionKey, ...opStatusActionKey[]];
