// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Status Clarification Reason (OpenPeppol)
 * @version 1.0
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/OPStatusReason/
 * @enum
 * @category Peppol Values
 */
export const opStatusReason = {
/**
* Indicates that receiver of the documents sends the message just to update the status and there are no problems with document processing
*/
"NON": "No Issue",
/**
* Indicates that the received document did not contain references as required by the receiver for correctly routing the document for approval or processing.
*/
"REF": "References incorrect",
/**
* Information in the received document is not according to legal requirements.
*/
"LEG": "Legal information incorrect",
/**
* The party to which the document is addressed is not known.
*/
"REC": "Receiver unknown",
/**
* Unacceptable or incorrect quality
*/
"QUA": "Item quality insufficient",
/**
* Delivery proposed or provided is not acceptable.
*/
"DEL": "Delivery issues",
/**
* Prices not according to previous expectation.
*/
"PRI": "Prices incorrect",
/**
* Quantity not according to previous expectation.
*/
"QTY": "Quantity incorrect",
/**
* Items not according to previous expectation.
*/
"ITM": "Items incorrect",
/**
* Payment terms not according to previous expectation.
*/
"PAY": "Payment terms incorrect",
/**
* Commercial transaction not recognized.
*/
"UNR": "Not recognized",
/**
* Finance terms not according to previous expectation.
*/
"FIN": "Finance incorrect",
/**
* Payment is partially but not fully paid.
*/
"PPD": "Partially Paid",
/**
* Reason for status is not defined by code.
*/
"OTH": "Other",

} as const;

/**
 * Keys of {@link opStatusReason}.
 */
export type opStatusReasonKey = "NON" | "REF" | "LEG" | "REC" | "QUA" | "DEL" | "PRI" | "QTY" | "ITM" | "PAY" | "UNR" | "FIN" | "PPD" | "OTH";
export const opStatusReasonKeys = [
  "NON",
  "REF",
  "LEG",
  "REC",
  "QUA",
  "DEL",
  "PRI",
  "QTY",
  "ITM",
  "PAY",
  "UNR",
  "FIN",
  "PPD",
  "OTH",
] as const satisfies readonly [opStatusReasonKey, ...opStatusReasonKey[]];
