// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @version 1.0
 *
 * @category Peppol Values
 *
 * @title Status Clarification Action (OpenPeppol)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/OPStatusAction/
 */
export const opStatusAction = {
  /**
   * @description No action required.
   */
  NOA: 'No action required',
  /**
   * @description Missing information requested without re-issuing invoice.
   */
  PIN: 'Provide information',
  /**
   * @description Request to re-issue a corrected invoice.
   */
  NIN: 'Issue new invoice',
  /**
   * @description Request to fully cancel the referenced invoice with a credit note.
   */
  CNF: 'Credit fully',
  /**
   * @description Request to issue partial credit note for corrections only.
   */
  CNP: 'Credit partially',
  /**
   * @description Request to repay the amount paid on the invoice.
   */
  CNA: 'Credit the amount',
  /**
   * @description Requested action is not defined by code.
   */
  OTH: 'Other',
};

/**
 * @description Keys of {@link opStatusAction}.
 */
export type OpStatusActionKeys = 'NOA' | 'PIN' | 'NIN' | 'CNF' | 'CNP' | 'CNA' | 'OTH';

/**
 * @description Keys of {@link opStatusAction}.
 */
export const opStatusActionKeys = ['NOA', 'PIN', 'NIN', 'CNF', 'CNP', 'CNA', 'OTH'] as const;
