// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @version 1.0
 *
 * @category Peppol Values
 *
 * @title Status Clarification Reason (OpenPeppol)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/OPStatusReason/
 */
export const opStatusReason = {
  /**
   * @description Indicates that receiver of the documents sends the message just to update the status and there are no problems with document processing.
   */
  NON: 'No Issue',
  /**
   * @description Indicates that the received document did not contain references as required by the receiver for correctly routing the document for approval or
   * processing.
   */
  REF: 'References incorrect',
  /**
   * @description Information in the received document is not according to legal requirements.
   */
  LEG: 'Legal information incorrect',
  /**
   * @description The party to which the document is addressed is not known.
   */
  REC: 'Receiver unknown',
  /**
   * @description Unacceptable or incorrect quality.
   */
  QUA: 'Item quality insufficient',
  /**
   * @description Delivery proposed or provided is not acceptable.
   */
  DEL: 'Delivery issues',
  /**
   * @description Prices not according to previous expectation.
   */
  PRI: 'Prices incorrect',
  /**
   * @description Quantity not according to previous expectation.
   */
  QTY: 'Quantity incorrect',
  /**
   * @description Items not according to previous expectation.
   */
  ITM: 'Items incorrect',
  /**
   * @description Payment terms not according to previous expectation.
   */
  PAY: 'Payment terms incorrect',
  /**
   * @description Commercial transaction not recognized.
   */
  UNR: 'Not recognized',
  /**
   * @description Finance terms not according to previous expectation.
   */
  FIN: 'Finance incorrect',
  /**
   * @description Payment is partially but not fully paid.
   */
  PPD: 'Partially Paid',
  /**
   * @description Reason for status is not defined by code.
   */
  OTH: 'Other',
} as const;

/**
 * @description Keys of {@link opStatusReason}.
 */
export type opStatusReasonKey = 'NON' | 'REF' | 'LEG' | 'REC' | 'QUA' | 'DEL' | 'PRI' | 'QTY' | 'ITM' | 'PAY' | 'UNR' | 'FIN' | 'PPD' | 'OTH';
export const opStatusReasonKeys = [
  'NON',
  'REF',
  'LEG',
  'REC',
  'QUA',
  'DEL',
  'PRI',
  'QTY',
  'ITM',
  'PAY',
  'UNR',
  'FIN',
  'PPD',
  'OTH',
] as const satisfies readonly [opStatusReasonKey, ...Array<opStatusReasonKey>];
