// oxlint-disable
/// Do not edit this file directly. It is generated by `packages/www/scripts/values.ts`

/**
 * @version 9.7
 *
 * @category Peppol Values
 *
 * @title Peppol Participant Identifier Schemes
 *
 * @enum
 */
export const participantIdentifierSchemes = {
  /**
   * @since 1.0.0
   *
   * @example
   *   `784301772``78430177200025`;
   *
   * @name `System Information et Repertoire des Entreprise et des Etablissements: SIRENE`
   *
   * @country `FR`
   *
   * @validation
   * ```regex
   * [0-9]{9}([0-9]{5})?
   * ```
   * Check digits: Luhn Algorithm
   */
  '0002': 'FR:SIRENE',
  /**
   * @since 1.0.0
   *
   * @example
   *   `2120000787`;
   *
   * @name `Organisationsnummer`
   *
   * @country `SE`
   *
   * @validation
   * ```regex
   * [0-9]{10}
   * ```
   * Check digits: Luhn Algorithm
   */
  '0007': 'SE:ORGNR',
  /**
   * @since 1.1.1
   *
   * @example
   *   `78430177200025`;
   *
   * @name `SIRET-CODE`
   *
   * @country `FR`
   *
   * @validation
   * ```regex
   * [0-9]{14}
   * ```
   */
  '0009': 'FR:SIRET',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `0037:00371234567800001``0037:1234567800001`;
   *
   * @name `LY-tunnus`
   *
   * @country `FI`
   *
   * @validation
   * ```regex
   * (0037)?[0-9]{7}-?[0-9][0-9A-Z]{0,5}
   * ```
   * Check Digit: mod11 of 8-digit OrgCode (weights 2, 4, 8, 5, 10, 9, 7 [right to left] or 7, 9, 10, 5, 8, 4, 2, 1 [left to right])
   */
  '0037': 'FI:OVT',
  /**
   * @since 1.0.0
   *
   * @example
   *   `812810734`;
   *
   * @name `Data Universal Numbering System (D-U-N-S Number)`
   *
   * @country `international`
   *
   * @validation
   * ```regex
   * [0-9]{9}
   * ```
   */
  '0060': 'DUNS',
  /**
   * @since 1.0.0
   *
   * @example
   *   `1548079098355`;
   *
   * @name `Global Location Number`
   *
   * @country `international`
   *
   * @validation
   * ```regex
   * [0-9]{13}
   * ```
   * Check Digit: mod10 (weights 1, 3)
   */
  '0088': 'GLN',
  /**
   * @since 1.0.0
   *
   * @name `The Danish Business Authority - P-number (DK:P)`
   *
   * @country `DK`
   *
   * @validation
   * ```regex
   * [0-9]{10}
   * ```
   */
  '0096': 'DK:P',
  /**
   * @since 1.0.0
   *
   * @name `FTI - Ediforum Italia`
   *
   * @country `IT`
   *
   * @validation
   * ```regex
   * [0-9]{11,16}
   * ```
   * The check digit algorithm is the one published in the Gazzetta Ufficiale no 345 of December 29 1976.
   */
  '0097': 'IT:FTI',
  /**
   * @since 1.1.2
   *
   * @name `Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme`
   *
   * @country `NL`
   *
   * @validation
   * ```regex
   * [0-9]{17}
   * ```
   * Check Digits: mod97
   */
  '0106': 'NL:KVK',
  /**
   * @since 4
   *
   * @name `Directorates of the European Commission`
   *
   * @country `international`
   */
  '0130': 'EU:NAL',
  /**
   * @since 1.0.0
   *
   * @name `SIA Object Identifiers`
   *
   * @country `IT`
   */
  '0135': 'IT:SIA',
  /**
   * @since 1.0.0
   *
   * @name `SECETI Object Identifiers`
   *
   * @country `IT`
   */
  '0142': 'IT:SECETI',
  /**
   * @since 5
   *
   * @example
   *   `51 824 753 556`;
   *
   * @name `Australian Business Number (ABN) Scheme`
   *
   * @country `AU`
   *
   * @validation
   * ```regex
   * [0-9]{11}
   * ```
   * Check number: mod 89 (weights)
   * * Subtract 1 from the first (left-most) digit of the ABN to give a new 11 digit number
   * * Multiply each of the digits in this new number by a "weighting factor" based on its position as shown in the table below
   * *Sum the resulting 11 products
   * * Divide the sum total by 89, noting the remainder
   * * If the remainder is zero the number is a valid ABN
   * Weight: 10, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
   */
  '0151': 'AU:ABN',
  /**
   * @since 9.7
   *
   * @name `Identification number of economic subject (ICO)`
   *
   * @country `SK`
   *
   * @validation
   * ```regex
   * [0-9]{8}
   * ```
   * Check number: mod11 (weights: 8, 7, 6, 5, 4, 3, 2)
   */
  '0158': 'SK:ICO',
  /**
   * @since 5
   *
   * @name `Swiss Unique Business Identification Number (UIDB)`
   *
   * @country `CH`
   *
   * @validation
   * ```regex
   * CHE[0-9]{9}
   * ```
   * Check number: mod11 (weights: 5, 4, 3, 2, 7, 6, 5, 4)
   */
  '0183': 'CH:UIDB',
  /**
   * @since 1.2.1
   *
   * @name `The Danish Business Authority - CVR-number (DK:CVR)`
   *
   * @country `DK`
   *
   * @validation
   * ```regex
   * [1-9][0-9]{7}
   * ```
   */
  '0184': 'DK:DIGST',
  /**
   * @since 8.1
   *
   * @name `Corporate Number of The Social Security and Tax Number System`
   *
   * @country `JP`
   */
  '0188': 'JP:SST',
  /**
   * @since 2
   *
   * @example
   *   `00000001820029336000`;
   *
   * @name `Organisatie-identificatienummer (OIN)`
   *
   * @country `NL`
   *
   * @validation
   * ```regex
   * [0-9]{20}
   * ```
   */
  '0190': 'NL:OINO',
  /**
   * @since 2
   *
   * @example
   *   `10137025`;
   *
   * @name `Company code`
   *
   * @country `EE`
   *
   * @validation
   * ```regex
   * [1789][0-9]{7}
   * ```
   * CheckDigit as last char.
   * Python code to check:
   * def calc_check_digit(number):
   * """Calculate the check digit."""
   * check = sum(((i % 9) + 1) * int(n)
   * for i, n in enumerate(number[:-1])) % 11
   * if check == 10:
   * check = sum((((i + 2) % 9) + 1) * int(n)
   * for i, n in enumerate(number[:-1])) % 11
   * return str(check % 10)
   */
  '0191': 'EE:CC',
  /**
   * @since 2
   *
   * @example
   *   `745707327`;
   *
   * @name `Organisasjonsnummer`
   *
   * @country `NO`
   *
   * @validation
   * ```regex
   * [0-9]{9}
   * ```
   * Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3)
   */
  '0192': 'NO:ORG',
  /**
   * @deprecated
   *
   * @since 3
   *
   * @name `UBL.BE Party Identifier`
   *
   * @country `BE`
   *
   * @validation
   * ```regex
   * .{4,50}
   * ```
   */
  '0193': 'UBLBE',
  /**
   * @since 4
   *
   * @name `Singapore Nationwide E-Invoice Framework`
   *
   * @country `SG`
   *
   * @validation
   * ```regex
   * [a-z]{2}[a-z]{3}([0-9]{8}|[0-9]{9}|[RST][0-9]{2}[a-z]{2}[0-9]{4})[0-9a-z]
   * ```
   */
  '0195': 'SG:UEN',
  /**
   * @since 4
   *
   * @name `Icelandic identifier`
   *
   * @country `IS`
   *
   * @validation
   * ```regex
   * [0-9]{10}
   * ```
   * Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3, 2)
   */
  '0196': 'IS:KTNR',
  /**
   * @since 5
   *
   * @name `The Danish Business Authority - SE-number (DK:SE)`
   *
   * @country `DK`
   *
   * @validation
   * ```regex
   * DK[0-9]{8}
   * ```
   * Check digit: mod11 (weights 2, 7, 6, 5, 4, 3, 2, 1)
   */
  '0198': 'DK:ERST',
  /**
   * @since 5
   *
   * @name `Legal Entity Identifier (LEI)`
   *
   * @country `international`
   *
   * @validation
   * ```regex
   * [A-Z0-9]{18}[0-9]{2}
   * ```
   * Check digit: mod97-10
   */
  '0199': 'LEI',
  /**
   * @since 5
   *
   * @example
   *   `111963319`;
   *
   * @name `Legal entity code`
   *
   * @country `LT`
   *
   * @validation
   * ```regex
   * [0-9]{9}
   * ```
   * Check number: see text
   */
  '0200': 'LT:LEC',
  /**
   * @since 6
   *
   * @name `Codice Univoco Unità Organizzativa iPA`
   *
   * @country `IT`
   *
   * @validation
   * ```regex
   * [0-9a-zA-Z]{6}
   * ```
   * No checkdigit
   */
  '0201': 'IT:CUUO',
  /**
   * @since 6
   *
   * @name `Peppol-Leitweg-ID`
   *
   * @country `DE`
   *
   * @validation
   * ```regex
   * [0-9]{2,12}(\-[0-9A-Z]{0,30})?\-[0-9]{2}
   * ```
   */
  '0204': 'DE:LWID',
  /**
   * @since 8.4
   *
   * @name `CODDEST`
   *
   * @country `IT`
   */
  '0205': 'IT:COD',
  /**
   * @since 7
   *
   * @name `Numero d'entreprise / ondernemingsnummer / Unternehmensnummer`
   *
   * @country `BE`
   *
   * @validation
   * ```regex
   * [01][0-9]{9}
   * ```
   * Check digit: mod97
   * See https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/vat.py
   */
  '0208': 'BE:EN',
  /**
   * @since 7.5
   *
   * @example
   *   `414541000099999325412345678901234567890`;
   *
   * @name `GS1 identification keys`
   *
   * @country `international`
   *
   * @validation
   * See document "GS1 Application Standard for usage of ISO/IEC 6523 International Code Designator (ICD) 0209"
   */
  '0209': 'GS1',
  /**
   * @since 7.5
   *
   * @name `CODICE FISCALE`
   *
   * @country `IT`
   *
   * @validation
   * Character Repertoire : A to Z (upper case) and 0 to 9
   */
  '0210': 'IT:CFI',
  /**
   * @since 7.5
   *
   * @name `PARTITA IVA`
   *
   * @country `IT`
   *
   * @validation
   * ```regex
   * IT[0-9]{11}
   * ```
   * first 7: company identifiers
   * next 3: province of residence (between "001" and "100"; or "120", "121", "888" "999")
   * Last: check digit
   * Check digit: Luhn
   */
  '0211': 'IT:IVA',
  /**
   * @deprecated
   *
   * @since 7.5
   *
   * @name `Finnish Organization Identifier`
   *
   * @country `FI`
   *
   * @validation
   * Character Repertoire: digits 0-9 and hyphen "-"
   */
  '0212': 'FI:ORG',
  /**
   * @deprecated
   *
   * @since 7.5
   *
   * @name `Finnish Organization Value Add Tax Identifier`
   *
   * @country `FI`
   *
   * @validation
   * Character Repertoire: digits 0-9 and FI
   */
  '0213': 'FI:VAT',
  /**
   * @deprecated
   *
   * @since 8.1
   *
   * @name `Net service ID`
   *
   * @country `FI`
   *
   * @validation
   * Character Repertoire: Letters A-Z, digits 0-9
   */
  '0215': 'FI:NSI',
  /**
   * @since 8.1
   *
   * @name `OVTcode`
   *
   * @country `FI`
   *
   * @validation
   * Character Repertoire: Capital letters A-Z, digits 0-9
   */
  '0216': 'FI:OVT2',
  /**
   * @since 8.8
   *
   * @name `Unified registration number`
   *
   * @country `LV`
   *
   * @validation
   * ```regex
   * [0-9]{9}([0-9]{2})?
   * ```
   */
  '0218': 'LV:URN',
  /**
   * @since 8.5
   *
   * @name `The registered number of the qualified invoice issuer`
   *
   * @country `JP`
   */
  '0221': 'JP:IIN',
  /**
   * @since 9.1
   *
   * @name `FRCTC Electronic Address`
   *
   * @country `FR`
   *
   * @validation
   * ```regex
   * [A-Z-a-z0-9_\-]{1,130}
   * ```
   */
  '0225': 'FR:CTC',
  /**
   * @since 8.5
   *
   * @name `National e-Invoicing Framework`
   *
   * @country `MY`
   */
  '0230': 'MY:EIF',
  /**
   * @since 9.1
   *
   * @name `UAE Tax Identification Number (TIN)`
   *
   * @country `AE`
   *
   * @validation
   * ```regex
   * 1[0-9]{9}
   * ```
   */
  '0235': 'AE:TIN',
  /**
   * @since 9.1
   *
   * @name `Register of legal persons`
   *
   * @country `LU`
   *
   * @validation
   * ```regex
   * [0-9]{11}
   * ```
   */
  '0240': 'LU:MAT',
  /**
   * @since 9.3
   *
   * @name `OpenPeppol Service Provider Identification Scheme`
   *
   * @country `international`
   *
   * @validation
   * ```regex
   * [0-9]{6}(-[0-9A-Z_]{3,12}(\.[0-9A-Z\-\._~]{3,24})?)?
   * ```
   */
  '0242': 'SPIS',
  /**
   * @since 9.5
   *
   * @name `Tax Identification (Tax ID)`
   *
   * @country `NG`
   *
   * @validation
   * ```regex
   * [0-9]{13}
   * ```
   */
  '0244': 'NG:TID',
  /**
   * @since 9.5
   *
   * @name `Tax identification number (DIČ)`
   *
   * @country `SK`
   *
   * @validation
   * ```regex
   * [0-9]{10}
   * ```
   */
  '0245': 'SK:DIC',
  /**
   * @since 9.5
   *
   * @name `German Electronic Business Address`
   *
   * @country `DE`
   *
   * @validation
   * ```regex
   * DE[0-9]{9}(-[0-9]{5})?(\.[0-9A-Z]{1,8})?
   * ```
   */
  '0246': 'DE:GEBA',
  /**
   * @since 9.6
   *
   * @example
   *   `OM1100003554`;
   *
   * @name `Oman Value Added Tax Identification Number (VATIN)`
   *
   * @country `OM`
   *
   * @validation
   * ```regex
   * OM[0-9]{10}
   * ```
   */
  '0248': 'OM:VAT',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @name `Danish Ministry of the Interior and Health`
   *
   * @country `DK`
   */
  '9901': 'DK:CPR',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `13585628`;
   *
   * @name `The Danish Commerce and Companies Agency`
   *
   * @country `DK`
   *
   * @validation
   * ```regex
   * [1-9][0-9]{7}
   * ```
   * Check digit: mod11 (weights, 2, 7, 6, 5, 4, 3, 2, 1)
   */
  '9902': 'DK:CVR',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `DK26769388`;
   *
   * @name `Danish Ministry of Taxation, Central Customs and Tax Administration`
   *
   * @country `DK`
   *
   * @validation
   * ```regex
   * DK[0-9]{8}
   * ```
   * Taks: validate Check digit: mod11 (weights 2, 7, 6, 5, 4, 3, 2, 1)
   */
  '9904': 'DK:SE',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `DK26769388`;
   *
   * @name `Danish VANS providers`
   *
   * @country `DK`
   */
  '9905': 'DK:VANS',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `IT06363391001`;
   *
   * @name `Ufficio responsabile gestione partite IVA`
   *
   * @country `IT`
   *
   * @validation
   * ```regex
   * IT[0-9]{11}
   * ```
   * first 7: company identifiers
   * next 3: province of residence (between "001" and "100"; or "120", "121", "888" "999")
   * Last: check digit
   * Check digit: Luhn
   */
  '9906': 'IT:VAT',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `RSSBBR69C48F839A`;
   *
   * @name `TAX Authority`
   *
   * @country `IT`
   *
   * @validation
   * ```regex
   * [0-9]{11} (company identification)
   * ```
   * first 7: company identifiers
   * next 3: province of residence (between "001" and "100"; or "120", "121", "888" "999")
   * Last: check digit
   * Check digit: Luhn
   *
   * ```regex
   * [A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z] (personal identification)
   * ```
   * Check digit: https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/it/codicefiscale.py
   */
  '9907': 'IT:CF',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @name `Enhetsregisteret ved Bronnoysundregisterne`
   *
   * @country `NO`
   *
   * @validation
   * ```regex
   * [0-9]{9}
   * ```
   * Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3)
   */
  '9908': 'NO:ORGNR',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @example
   *   `990399123MVA`;
   *
   * @name `Norwegian VAT number`
   *
   * @country `NO`
   *
   * @validation
   * ```regex
   * NO[0-9]{9}MVA
   * ```
   * Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3)
   */
  '9909': 'NO:VAT',
  /**
   * @since 1.0.0
   *
   * @name `Hungary VAT number`
   *
   * @country `HU`
   *
   * @validation
   * ```regex
   * HU[0-9]{8}
   * ```
   * Check digit: https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/hu/anum.py
   */
  '9910': 'HU:VAT',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @name `National ministries of Economy`
   *
   * @country `international`
   *
   * @validation
   * ```regex
   * [A-Z]{2}[A-Z0-9]{,20}
   * ```
   */
  '9912': 'EU:VAT',
  /**
   * @since 1.0.0
   *
   * @name `Business Registers Network`
   *
   * @country `international`
   */
  '9913': 'EU:REID',
  /**
   * @since 1.0.0
   *
   * @example
   *   `ATU12345678`;
   *
   * @name `Österreichische Umsatzsteuer-Identifikationsnummer`
   *
   * @country `AT`
   */
  '9914': 'AT:VAT',
  /**
   * @since 1.0.0
   *
   * @example
   *   `b`;
   *
   * @name `Österreichisches Verwaltungs bzw. Organisationskennzeichen`
   *
   * @country `AT`
   *
   * @validation
   * ```regex
   * [A-Z][A-Z0-9]*
   * ```
   */
  '9915': 'AT:GOV',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @name `Firmenidentifikationsnummer der Statistik Austria`
   *
   * @country `AT`
   */
  '9916': 'AT:CID',
  /**
   * @deprecated
   *
   * @since 1.0.0
   *
   * @name `Icelandic National Registry`
   *
   * @country `IS`
   *
   * @validation
   * ```regex
   * [0-9]{10}
   * ```
   * Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3, 2)
   */
  '9917': 'IS:KT',
  /**
   * @since 1.0.1
   *
   * @name `SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T`
   *
   * @country `international`
   */
  '9918': 'IBAN',
  /**
   * @since 1.0.2
   *
   * @name `Kennziffer des Unternehmensregisters`
   *
   * @country `AT`
   */
  '9919': 'AT:KUR',
  /**
   * @since 1.0.2
   *
   * @name `Agencia Española de Administración Tributaria`
   *
   * @country `ES`
   */
  '9920': 'ES:VAT',
  /**
   * @deprecated
   *
   * @since 1.1.0
   *
   * @name `Indice delle Pubbliche Amministrazioni`
   *
   * @country `IT`
   */
  '9921': 'IT:IPA',
  /**
   * @since 1.1.0
   *
   * @name `Andorra VAT number`
   *
   * @country `AD`
   */
  '9922': 'AD:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Albania VAT number`
   *
   * @country `AL`
   */
  '9923': 'AL:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Bosnia and Herzegovina VAT number`
   *
   * @country `BA`
   */
  '9924': 'BA:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Belgium VAT number`
   *
   * @country `BE`
   */
  '9925': 'BE:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Bulgaria VAT number`
   *
   * @country `BG`
   */
  '9926': 'BG:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Switzerland VAT number`
   *
   * @country `CH`
   */
  '9927': 'CH:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Cyprus VAT number`
   *
   * @country `CY`
   */
  '9928': 'CY:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Czech Republic VAT number`
   *
   * @country `CZ`
   */
  '9929': 'CZ:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Germany VAT number`
   *
   * @country `DE`
   */
  '9930': 'DE:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Estonia VAT number`
   *
   * @country `EE`
   */
  '9931': 'EE:VAT',
  /**
   * @since 1.1.0
   *
   * @name `United Kingdom VAT number`
   *
   * @country `GB`
   */
  '9932': 'GB:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Greece VAT number`
   *
   * @country `GR`
   */
  '9933': 'GR:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Croatia VAT number`
   *
   * @country `HR`
   */
  '9934': 'HR:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Ireland VAT number`
   *
   * @country `IE`
   */
  '9935': 'IE:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Liechtenstein VAT number`
   *
   * @country `LI`
   */
  '9936': 'LI:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Lithuania VAT number`
   *
   * @country `LT`
   */
  '9937': 'LT:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Luxemburg VAT number`
   *
   * @country `LU`
   */
  '9938': 'LU:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Latvia VAT number`
   *
   * @country `LV`
   */
  '9939': 'LV:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Monaco VAT number`
   *
   * @country `MC`
   */
  '9940': 'MC:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Montenegro VAT number`
   *
   * @country `ME`
   */
  '9941': 'ME:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Macedonia, the former Yugoslav Republic of VAT number`
   *
   * @country `MK`
   */
  '9942': 'MK:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Malta VAT number`
   *
   * @country `MT`
   */
  '9943': 'MT:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Netherlands VAT number`
   *
   * @country `NL`
   */
  '9944': 'NL:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Poland VAT number`
   *
   * @country `PL`
   */
  '9945': 'PL:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Portugal VAT number`
   *
   * @country `PT`
   */
  '9946': 'PT:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Romania VAT number`
   *
   * @country `RO`
   */
  '9947': 'RO:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Serbia VAT number`
   *
   * @country `RS`
   */
  '9948': 'RS:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Slovenia VAT number`
   *
   * @country `SI`
   */
  '9949': 'SI:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Slovakia VAT number`
   *
   * @country `SK`
   */
  '9950': 'SK:VAT',
  /**
   * @since 1.1.0
   *
   * @name `San Marino VAT number`
   *
   * @country `SM`
   */
  '9951': 'SM:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Turkey VAT number`
   *
   * @country `TR`
   */
  '9952': 'TR:VAT',
  /**
   * @since 1.1.0
   *
   * @name `Holy See (Vatican City State) VAT number`
   *
   * @country `VA`
   */
  '9953': 'VA:VAT',
  /**
   * @deprecated
   *
   * @since 1.1.3
   *
   * @name `Dutch Originator's Identification Number`
   *
   * @country `NL`
   */
  '9954': 'NL:OIN',
  /**
   * @deprecated
   *
   * @since 1.2.0
   *
   * @name `Swedish VAT number`
   *
   * @country `SE`
   */
  '9955': 'SE:VAT',
  /**
   * @deprecated
   *
   * @since 1.2.1
   *
   * @example
   *   `0899965307`;
   *
   * @name `Belgian Crossroad Bank of Enterprise number`
   *
   * @country `BE`
   *
   * @validation
   * ```regex
   * 0[0-9]{9}
   * ```
   * Check digit: mod97
   * See https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/vat.py
   */
  '9956': 'BE:CBE',
  /**
   * @since 1.2.1
   *
   * @name `French VAT number`
   *
   * @country `FR`
   */
  '9957': 'FR:VAT',
  /**
   * @deprecated
   *
   * @since 3
   *
   * @name `Peppol-Leitweg-ID`
   *
   * @country `DE`
   */
  '9958': 'DE:LID',
  /**
   * @since 8.3
   *
   * @name `US Employer ID Number`
   *
   * @country `US`
   */
  '9959': 'US:EIN',
};

/**
 * @description Keys of {@link participantIdentifierSchemes}.
 */
export const participantIdentifierSchemesKeys = [
  '0002',
  '0007',
  '0009',
  '0037',
  '0060',
  '0088',
  '0096',
  '0097',
  '0106',
  '0130',
  '0135',
  '0142',
  '0151',
  '0158',
  '0183',
  '0184',
  '0188',
  '0190',
  '0191',
  '0192',
  '0193',
  '0195',
  '0196',
  '0198',
  '0199',
  '0200',
  '0201',
  '0204',
  '0205',
  '0208',
  '0209',
  '0210',
  '0211',
  '0212',
  '0213',
  '0215',
  '0216',
  '0218',
  '0221',
  '0225',
  '0230',
  '0235',
  '0240',
  '0242',
  '0244',
  '0245',
  '0246',
  '0248',
  '9901',
  '9902',
  '9904',
  '9905',
  '9906',
  '9907',
  '9908',
  '9909',
  '9910',
  '9912',
  '9913',
  '9914',
  '9915',
  '9916',
  '9917',
  '9918',
  '9919',
  '9920',
  '9921',
  '9922',
  '9923',
  '9924',
  '9925',
  '9926',
  '9927',
  '9928',
  '9929',
  '9930',
  '9931',
  '9932',
  '9933',
  '9934',
  '9935',
  '9936',
  '9937',
  '9938',
  '9939',
  '9940',
  '9941',
  '9942',
  '9943',
  '9944',
  '9945',
  '9946',
  '9947',
  '9948',
  '9949',
  '9950',
  '9951',
  '9952',
  '9953',
  '9954',
  '9955',
  '9956',
  '9957',
  '9958',
  '9959',
] as const;

/**
 * @description The list of elements that are deprecated.
 */
export const deprecatedParticipantIdentifierSchemes = [
  '0037',
  '0193',
  '0212',
  '0213',
  '0215',
  '9901',
  '9902',
  '9904',
  '9905',
  '9906',
  '9907',
  '9908',
  '9909',
  '9912',
  '9916',
  '9917',
  '9921',
  '9954',
  '9955',
  '9956',
  '9958',
];
