// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `packages/www/scripts/values.ts`

/**
 * @title Peppol Participant Identifier Schemes
 * @version 9.7
 * @enum
 * @category Peppol Values
 */
export const participantIdentifierSchemes = {
/**
* @name `System Information et Repertoire des Entreprise et des Etablissements: SIRENE`
* @country `FR`
* @since 1.0.0
* @example 
* `784301772`
* `78430177200025`
* @validation 
* ```regex
* [0-9]{9}([0-9]{5})?
* ```
* Check digits: Luhn Algorithm
*/
"0002": "FR:SIRENE",
/**
* @name `Organisationsnummer`
* @country `SE`
* @since 1.0.0
* @example 
* `2120000787`
* @validation 
* ```regex
* [0-9]{10}
* ```
* Check digits: Luhn Algorithm
*/
"0007": "SE:ORGNR",
/**
* @name `SIRET-CODE`
* @country `FR`
* @since 1.1.1
* @example 
* `78430177200025`
* @validation 
* ```regex
* [0-9]{14}
* ```
*/
"0009": "FR:SIRET",
/**
* @name `LY-tunnus`
* @country `FI`
* @since 1.0.0
* @deprecated
* @example 
* `0037:00371234567800001`
* `0037:1234567800001`
* @validation 
* ```regex
* (0037)?[0-9]{7}-?[0-9][0-9A-Z]{0,5}
* ```
* Check Digit: mod11 of 8-digit OrgCode (weights 2, 4, 8, 5, 10, 9, 7 [right to left] or 7, 9, 10, 5, 8, 4, 2, 1 [left to right])
*/
"0037": "FI:OVT",
/**
* @name `Data Universal Numbering System (D-U-N-S Number)`
* @country `international`
* @since 1.0.0
* @example 
* `812810734`
* @validation 
* ```regex
* [0-9]{9}
* ```
*/
"0060": "DUNS",
/**
* @name `Global Location Number`
* @country `international`
* @since 1.0.0
* @example 
* `1548079098355`
* @validation 
* ```regex
* [0-9]{13}
* ```
* Check Digit: mod10 (weights 1, 3)
*/
"0088": "GLN",
/**
* @name `The Danish Business Authority - P-number (DK:P)`
* @country `DK`
* @since 1.0.0
* @validation 
* ```regex
* [0-9]{10}
* ```
*/
"0096": "DK:P",
/**
* @name `FTI - Ediforum Italia`
* @country `IT`
* @since 1.0.0
* @validation 
* ```regex
* [0-9]{11,16}
* ```
* The check digit algorithm is the one published in the Gazzetta Ufficiale no 345 of December 29 1976.
*/
"0097": "IT:FTI",
/**
* @name `Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme`
* @country `NL`
* @since 1.1.2
* @validation 
* ```regex
* [0-9]{17}
* ```
* Check Digits: mod97
*/
"0106": "NL:KVK",
/**
* @name `Directorates of the European Commission`
* @country `international`
* @since 4
*/
"0130": "EU:NAL",
/**
* @name `SIA Object Identifiers`
* @country `IT`
* @since 1.0.0
*/
"0135": "IT:SIA",
/**
* @name `SECETI Object Identifiers`
* @country `IT`
* @since 1.0.0
*/
"0142": "IT:SECETI",
/**
* @name `Australian Business Number (ABN) Scheme`
* @country `AU`
* @since 5
* @example 
* `51 824 753 556`
* @validation 
* ```regex
* [0-9]{11}
* ```
* Check number: mod 89 (weights)
* * Subtract 1 from the first (left-most) digit of the ABN to give a new 11 digit number
* * Multiply each of the digits in this new number by a "weighting factor" based on its position as shown in the table below
* *Sum the resulting 11 products
* * Divide the sum total by 89, noting the remainder
* * If the remainder is zero the number is a valid ABN
* Weight: 10, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
*/
"0151": "AU:ABN",
/**
* @name `Identification number of economic subject (ICO)`
* @country `SK`
* @since 9.7
* @validation 
* ```regex
* [0-9]{8}
* ```
* Check number: mod11 (weights: 8, 7, 6, 5, 4, 3, 2)
*/
"0158": "SK:ICO",
/**
* @name `Swiss Unique Business Identification Number (UIDB)`
* @country `CH`
* @since 5
* @validation 
* ```regex
* CHE[0-9]{9}
* ```
* Check number: mod11 (weights: 5, 4, 3, 2, 7, 6, 5, 4)
*/
"0183": "CH:UIDB",
/**
* @name `The Danish Business Authority - CVR-number (DK:CVR)`
* @country `DK`
* @since 1.2.1
* @validation 
* ```regex
* [1-9][0-9]{7}
* ```
*/
"0184": "DK:DIGST",
/**
* @name `Corporate Number of The Social Security and Tax Number System`
* @country `JP`
* @since 8.1
*/
"0188": "JP:SST",
/**
* @name `Organisatie-identificatienummer (OIN)`
* @country `NL`
* @since 2
* @example 
* `00000001820029336000`
* @validation 
* ```regex
* [0-9]{20}
* ```
*/
"0190": "NL:OINO",
/**
* @name `Company code`
* @country `EE`
* @since 2
* @example 
* `10137025`
* @validation 
* ```regex
* [1789][0-9]{7}
* ```
* CheckDigit as last char.
* Python code to check:
* def calc_check_digit(number):
* """Calculate the check digit."""
* check = sum(((i % 9) + 1) * int(n)
* for i, n in enumerate(number[:-1])) % 11
* if check == 10:
* check = sum((((i + 2) % 9) + 1) * int(n)
* for i, n in enumerate(number[:-1])) % 11
* return str(check % 10)
*/
"0191": "EE:CC",
/**
* @name `Organisasjonsnummer`
* @country `NO`
* @since 2
* @example 
* `745707327`
* @validation 
* ```regex
* [0-9]{9}
* ```
* Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3)
*/
"0192": "NO:ORG",
/**
* @name `UBL.BE Party Identifier`
* @country `BE`
* @since 3
* @deprecated
* @validation 
* ```regex
* .{4,50}
* ```
*/
"0193": "UBLBE",
/**
* @name `Singapore Nationwide E-Invoice Framework`
* @country `SG`
* @since 4
* @validation 
* ```regex
* [a-z]{2}[a-z]{3}([0-9]{8}|[0-9]{9}|[RST][0-9]{2}[a-z]{2}[0-9]{4})[0-9a-z]
* ```
*/
"0195": "SG:UEN",
/**
* @name `Icelandic identifier`
* @country `IS`
* @since 4
* @validation 
* ```regex
* [0-9]{10}
* ```
* Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3, 2)
*/
"0196": "IS:KTNR",
/**
* @name `The Danish Business Authority - SE-number (DK:SE)`
* @country `DK`
* @since 5
* @validation 
* ```regex
* DK[0-9]{8}
* ```
* Check digit: mod11 (weights 2, 7, 6, 5, 4, 3, 2, 1)
*/
"0198": "DK:ERST",
/**
* @name `Legal Entity Identifier (LEI)`
* @country `international`
* @since 5
* @validation 
* ```regex
* [A-Z0-9]{18}[0-9]{2}
* ```
* Check digit: mod97-10
*/
"0199": "LEI",
/**
* @name `Legal entity code`
* @country `LT`
* @since 5
* @example 
* `111963319`
* @validation 
* ```regex
* [0-9]{9}
* ```
* Check number: see text
*/
"0200": "LT:LEC",
/**
* @name `Codice Univoco Unità Organizzativa iPA`
* @country `IT`
* @since 6
* @validation 
* ```regex
* [0-9a-zA-Z]{6}
* ```
* No checkdigit
*/
"0201": "IT:CUUO",
/**
* @name `Peppol-Leitweg-ID`
* @country `DE`
* @since 6
* @validation 
* ```regex
* [0-9]{2,12}(\-[0-9A-Z]{0,30})?\-[0-9]{2}
* ```
*/
"0204": "DE:LWID",
/**
* @name `CODDEST`
* @country `IT`
* @since 8.4
*/
"0205": "IT:COD",
/**
* @name `Numero d'entreprise / ondernemingsnummer / Unternehmensnummer`
* @country `BE`
* @since 7
* @validation 
* ```regex
* [01][0-9]{9}
* ```
* Check digit: mod97
* See https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/vat.py
*/
"0208": "BE:EN",
/**
* @name `GS1 identification keys`
* @country `international`
* @since 7.5
* @example 
* `414541000099999325412345678901234567890`
* @validation 
* See document "GS1 Application Standard for usage of ISO/IEC 6523 International Code Designator (ICD) 0209"
*/
"0209": "GS1",
/**
* @name `CODICE FISCALE`
* @country `IT`
* @since 7.5
* @validation 
* Character Repertoire : A to Z (upper case) and 0 to 9
*/
"0210": "IT:CFI",
/**
* @name `PARTITA IVA`
* @country `IT`
* @since 7.5
* @validation 
* ```regex
* IT[0-9]{11}
* ```
* first 7: company identifiers
* next 3: province of residence (between "001" and "100"; or "120", "121", "888" "999")
* Last: check digit
* Check digit: Luhn
*/
"0211": "IT:IVA",
/**
* @name `Finnish Organization Identifier`
* @country `FI`
* @since 7.5
* @deprecated
* @validation 
* Character Repertoire: digits 0-9 and hyphen "-"
*/
"0212": "FI:ORG",
/**
* @name `Finnish Organization Value Add Tax Identifier`
* @country `FI`
* @since 7.5
* @deprecated
* @validation 
* Character Repertoire: digits 0-9 and FI
*/
"0213": "FI:VAT",
/**
* @name `Net service ID`
* @country `FI`
* @since 8.1
* @deprecated
* @validation 
* Character Repertoire: Letters A-Z, digits 0-9
*/
"0215": "FI:NSI",
/**
* @name `OVTcode`
* @country `FI`
* @since 8.1
* @validation 
* Character Repertoire: Capital letters A-Z, digits 0-9
*/
"0216": "FI:OVT2",
/**
* @name `Unified registration number`
* @country `LV`
* @since 8.8
* @validation 
* ```regex
* [0-9]{9}([0-9]{2})?
* ```
*/
"0218": "LV:URN",
/**
* @name `The registered number of the qualified invoice issuer`
* @country `JP`
* @since 8.5
*/
"0221": "JP:IIN",
/**
* @name `FRCTC Electronic Address`
* @country `FR`
* @since 9.1
* @validation 
* ```regex
* [A-Z-a-z0-9_\-]{1,130}
* ```
*/
"0225": "FR:CTC",
/**
* @name `National e-Invoicing Framework`
* @country `MY`
* @since 8.5
*/
"0230": "MY:EIF",
/**
* @name `UAE Tax Identification Number (TIN)`
* @country `AE`
* @since 9.1
* @validation 
* ```regex
* 1[0-9]{9}
* ```
*/
"0235": "AE:TIN",
/**
* @name `Register of legal persons`
* @country `LU`
* @since 9.1
* @validation 
* ```regex
* [0-9]{11}
* ```
*/
"0240": "LU:MAT",
/**
* @name `OpenPeppol Service Provider Identification Scheme`
* @country `international`
* @since 9.3
* @validation 
* ```regex
* [0-9]{6}(-[0-9A-Z_]{3,12}(\.[0-9A-Z\-\._~]{3,24})?)?
* ```
*/
"0242": "SPIS",
/**
* @name `Tax Identification (Tax ID)`
* @country `NG`
* @since 9.5
* @validation 
* ```regex
* [0-9]{13}
* ```
*/
"0244": "NG:TID",
/**
* @name `Tax identification number (DIČ)`
* @country `SK`
* @since 9.5
* @validation 
* ```regex
* [0-9]{10}
* ```
*/
"0245": "SK:DIC",
/**
* @name `German Electronic Business Address`
* @country `DE`
* @since 9.5
* @validation 
* ```regex
* DE[0-9]{9}(-[0-9]{5})?(\.[0-9A-Z]{1,8})?
* ```
*/
"0246": "DE:GEBA",
/**
* @name `Oman Value Added Tax Identification Number (VATIN)`
* @country `OM`
* @since 9.6
* @example 
* `OM1100003554`
* @validation 
* ```regex
* OM[0-9]{10}
* ```
*/
"0248": "OM:VAT",
/**
* @name `Danish Ministry of the Interior and Health`
* @country `DK`
* @since 1.0.0
* @deprecated
*/
"9901": "DK:CPR",
/**
* @name `The Danish Commerce and Companies Agency`
* @country `DK`
* @since 1.0.0
* @deprecated
* @example 
* `13585628`
* @validation 
* ```regex
* [1-9][0-9]{7}
* ```
* Check digit: mod11 (weights, 2, 7, 6, 5, 4, 3, 2, 1)
*/
"9902": "DK:CVR",
/**
* @name `Danish Ministry of Taxation, Central Customs and Tax Administration`
* @country `DK`
* @since 1.0.0
* @deprecated
* @example 
* `DK26769388`
* @validation 
* ```regex
* DK[0-9]{8}
* ```
* Taks: validate Check digit: mod11 (weights 2, 7, 6, 5, 4, 3, 2, 1)
*/
"9904": "DK:SE",
/**
* @name `Danish VANS providers`
* @country `DK`
* @since 1.0.0
* @deprecated
* @example 
* `DK26769388`
*/
"9905": "DK:VANS",
/**
* @name `Ufficio responsabile gestione partite IVA`
* @country `IT`
* @since 1.0.0
* @deprecated
* @example 
* `IT06363391001`
* @validation 
* ```regex
* IT[0-9]{11}
* ```
* first 7: company identifiers
* next 3: province of residence (between "001" and "100"; or "120", "121", "888" "999")
* Last: check digit
* Check digit: Luhn
*/
"9906": "IT:VAT",
/**
* @name `TAX Authority`
* @country `IT`
* @since 1.0.0
* @deprecated
* @example 
* `RSSBBR69C48F839A`
* @validation 
* ```regex
* [0-9]{11} (company identification)
* ```
* first 7: company identifiers
* next 3: province of residence (between "001" and "100"; or "120", "121", "888" "999")
* Last: check digit
* Check digit: Luhn
* 
* ```regex
* [A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z] (personal identification)
* ```
* Check digit: https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/it/codicefiscale.py
*/
"9907": "IT:CF",
/**
* @name `Enhetsregisteret ved Bronnoysundregisterne`
* @country `NO`
* @since 1.0.0
* @deprecated
* @validation 
* ```regex
* [0-9]{9}
* ```
* Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3)
*/
"9908": "NO:ORGNR",
/**
* @name `Norwegian VAT number`
* @country `NO`
* @since 1.0.0
* @deprecated
* @example 
* `990399123MVA`
* @validation 
* ```regex
* NO[0-9]{9}MVA
* ```
* Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3)
*/
"9909": "NO:VAT",
/**
* @name `Hungary VAT number`
* @country `HU`
* @since 1.0.0
* @validation 
* ```regex
* HU[0-9]{8}
* ```
* Check digit: https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/hu/anum.py
*/
"9910": "HU:VAT",
/**
* @name `National ministries of Economy`
* @country `international`
* @since 1.0.0
* @deprecated
* @validation 
* ```regex
* [A-Z]{2}[A-Z0-9]{,20}
* ```
*/
"9912": "EU:VAT",
/**
* @name `Business Registers Network`
* @country `international`
* @since 1.0.0
*/
"9913": "EU:REID",
/**
* @name `Österreichische Umsatzsteuer-Identifikationsnummer`
* @country `AT`
* @since 1.0.0
* @example 
* `ATU12345678`
*/
"9914": "AT:VAT",
/**
* @name `Österreichisches Verwaltungs bzw. Organisationskennzeichen`
* @country `AT`
* @since 1.0.0
* @example 
* `b`
* @validation 
* ```regex
* [A-Z][A-Z0-9]*
* ```
*/
"9915": "AT:GOV",
/**
* @name `Firmenidentifikationsnummer der Statistik Austria`
* @country `AT`
* @since 1.0.0
* @deprecated
*/
"9916": "AT:CID",
/**
* @name `Icelandic National Registry`
* @country `IS`
* @since 1.0.0
* @deprecated
* @validation 
* ```regex
* [0-9]{10}
* ```
* Check digit: mod11 (weights 3, 2, 7, 6, 5, 4, 3, 2)
*/
"9917": "IS:KT",
/**
* @name `SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T`
* @country `international`
* @since 1.0.1
*/
"9918": "IBAN",
/**
* @name `Kennziffer des Unternehmensregisters`
* @country `AT`
* @since 1.0.2
*/
"9919": "AT:KUR",
/**
* @name `Agencia Española de Administración Tributaria`
* @country `ES`
* @since 1.0.2
*/
"9920": "ES:VAT",
/**
* @name `Indice delle Pubbliche Amministrazioni`
* @country `IT`
* @since 1.1.0
* @deprecated
*/
"9921": "IT:IPA",
/**
* @name `Andorra VAT number`
* @country `AD`
* @since 1.1.0
*/
"9922": "AD:VAT",
/**
* @name `Albania VAT number`
* @country `AL`
* @since 1.1.0
*/
"9923": "AL:VAT",
/**
* @name `Bosnia and Herzegovina VAT number`
* @country `BA`
* @since 1.1.0
*/
"9924": "BA:VAT",
/**
* @name `Belgium VAT number`
* @country `BE`
* @since 1.1.0
*/
"9925": "BE:VAT",
/**
* @name `Bulgaria VAT number`
* @country `BG`
* @since 1.1.0
*/
"9926": "BG:VAT",
/**
* @name `Switzerland VAT number`
* @country `CH`
* @since 1.1.0
*/
"9927": "CH:VAT",
/**
* @name `Cyprus VAT number`
* @country `CY`
* @since 1.1.0
*/
"9928": "CY:VAT",
/**
* @name `Czech Republic VAT number`
* @country `CZ`
* @since 1.1.0
*/
"9929": "CZ:VAT",
/**
* @name `Germany VAT number`
* @country `DE`
* @since 1.1.0
*/
"9930": "DE:VAT",
/**
* @name `Estonia VAT number`
* @country `EE`
* @since 1.1.0
*/
"9931": "EE:VAT",
/**
* @name `United Kingdom VAT number`
* @country `GB`
* @since 1.1.0
*/
"9932": "GB:VAT",
/**
* @name `Greece VAT number`
* @country `GR`
* @since 1.1.0
*/
"9933": "GR:VAT",
/**
* @name `Croatia VAT number`
* @country `HR`
* @since 1.1.0
*/
"9934": "HR:VAT",
/**
* @name `Ireland VAT number`
* @country `IE`
* @since 1.1.0
*/
"9935": "IE:VAT",
/**
* @name `Liechtenstein VAT number`
* @country `LI`
* @since 1.1.0
*/
"9936": "LI:VAT",
/**
* @name `Lithuania VAT number`
* @country `LT`
* @since 1.1.0
*/
"9937": "LT:VAT",
/**
* @name `Luxemburg VAT number`
* @country `LU`
* @since 1.1.0
*/
"9938": "LU:VAT",
/**
* @name `Latvia VAT number`
* @country `LV`
* @since 1.1.0
*/
"9939": "LV:VAT",
/**
* @name `Monaco VAT number`
* @country `MC`
* @since 1.1.0
*/
"9940": "MC:VAT",
/**
* @name `Montenegro VAT number`
* @country `ME`
* @since 1.1.0
*/
"9941": "ME:VAT",
/**
* @name `Macedonia, the former Yugoslav Republic of VAT number`
* @country `MK`
* @since 1.1.0
*/
"9942": "MK:VAT",
/**
* @name `Malta VAT number`
* @country `MT`
* @since 1.1.0
*/
"9943": "MT:VAT",
/**
* @name `Netherlands VAT number`
* @country `NL`
* @since 1.1.0
*/
"9944": "NL:VAT",
/**
* @name `Poland VAT number`
* @country `PL`
* @since 1.1.0
*/
"9945": "PL:VAT",
/**
* @name `Portugal VAT number`
* @country `PT`
* @since 1.1.0
*/
"9946": "PT:VAT",
/**
* @name `Romania VAT number`
* @country `RO`
* @since 1.1.0
*/
"9947": "RO:VAT",
/**
* @name `Serbia VAT number`
* @country `RS`
* @since 1.1.0
*/
"9948": "RS:VAT",
/**
* @name `Slovenia VAT number`
* @country `SI`
* @since 1.1.0
*/
"9949": "SI:VAT",
/**
* @name `Slovakia VAT number`
* @country `SK`
* @since 1.1.0
*/
"9950": "SK:VAT",
/**
* @name `San Marino VAT number`
* @country `SM`
* @since 1.1.0
*/
"9951": "SM:VAT",
/**
* @name `Turkey VAT number`
* @country `TR`
* @since 1.1.0
*/
"9952": "TR:VAT",
/**
* @name `Holy See (Vatican City State) VAT number`
* @country `VA`
* @since 1.1.0
*/
"9953": "VA:VAT",
/**
* @name `Dutch Originator's Identification Number`
* @country `NL`
* @since 1.1.3
* @deprecated
*/
"9954": "NL:OIN",
/**
* @name `Swedish VAT number`
* @country `SE`
* @since 1.2.0
* @deprecated
*/
"9955": "SE:VAT",
/**
* @name `Belgian Crossroad Bank of Enterprise number`
* @country `BE`
* @since 1.2.1
* @deprecated
* @example 
* `0899965307`
* @validation 
* ```regex
* 0[0-9]{9}
* ```
* Check digit: mod97
* See https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/vat.py
*/
"9956": "BE:CBE",
/**
* @name `French VAT number`
* @country `FR`
* @since 1.2.1
*/
"9957": "FR:VAT",
/**
* @name `Peppol-Leitweg-ID`
* @country `DE`
* @since 3
* @deprecated
*/
"9958": "DE:LID",
/**
* @name `US Employer ID Number`
* @country `US`
* @since 8.3
*/
"9959": "US:EIN",
} as const;

/**
 * Keys of {@link participantIdentifierSchemes}.
 */
export type participantIdentifierSchemesKey = "0002" | "0007" | "0009" | "0037" | "0060" | "0088" | "0096" | "0097" | "0106" | "0130" | "0135" | "0142" | "0151" | "0158" | "0183" | "0184" | "0188" | "0190" | "0191" | "0192" | "0193" | "0195" | "0196" | "0198" | "0199" | "0200" | "0201" | "0204" | "0205" | "0208" | "0209" | "0210" | "0211" | "0212" | "0213" | "0215" | "0216" | "0218" | "0221" | "0225" | "0230" | "0235" | "0240" | "0242" | "0244" | "0245" | "0246" | "0248" | "9901" | "9902" | "9904" | "9905" | "9906" | "9907" | "9908" | "9909" | "9910" | "9912" | "9913" | "9914" | "9915" | "9916" | "9917" | "9918" | "9919" | "9920" | "9921" | "9922" | "9923" | "9924" | "9925" | "9926" | "9927" | "9928" | "9929" | "9930" | "9931" | "9932" | "9933" | "9934" | "9935" | "9936" | "9937" | "9938" | "9939" | "9940" | "9941" | "9942" | "9943" | "9944" | "9945" | "9946" | "9947" | "9948" | "9949" | "9950" | "9951" | "9952" | "9953" | "9954" | "9955" | "9956" | "9957" | "9958" | "9959";
export const participantIdentifierSchemesKeys = [
  "0002",
  "0007",
  "0009",
  "0037",
  "0060",
  "0088",
  "0096",
  "0097",
  "0106",
  "0130",
  "0135",
  "0142",
  "0151",
  "0158",
  "0183",
  "0184",
  "0188",
  "0190",
  "0191",
  "0192",
  "0193",
  "0195",
  "0196",
  "0198",
  "0199",
  "0200",
  "0201",
  "0204",
  "0205",
  "0208",
  "0209",
  "0210",
  "0211",
  "0212",
  "0213",
  "0215",
  "0216",
  "0218",
  "0221",
  "0225",
  "0230",
  "0235",
  "0240",
  "0242",
  "0244",
  "0245",
  "0246",
  "0248",
  "9901",
  "9902",
  "9904",
  "9905",
  "9906",
  "9907",
  "9908",
  "9909",
  "9910",
  "9912",
  "9913",
  "9914",
  "9915",
  "9916",
  "9917",
  "9918",
  "9919",
  "9920",
  "9921",
  "9922",
  "9923",
  "9924",
  "9925",
  "9926",
  "9927",
  "9928",
  "9929",
  "9930",
  "9931",
  "9932",
  "9933",
  "9934",
  "9935",
  "9936",
  "9937",
  "9938",
  "9939",
  "9940",
  "9941",
  "9942",
  "9943",
  "9944",
  "9945",
  "9946",
  "9947",
  "9948",
  "9949",
  "9950",
  "9951",
  "9952",
  "9953",
  "9954",
  "9955",
  "9956",
  "9957",
  "9958",
  "9959",
] as const satisfies readonly [participantIdentifierSchemesKey, ...participantIdentifierSchemesKey[]];

/**
 * The list of elements that are deprecated.
 */
export const deprecatedparticipantIdentifierSchemes = [
  "0037",
  "0193",
  "0212",
  "0213",
  "0215",
  "9901",
  "9902",
  "9904",
  "9905",
  "9906",
  "9907",
  "9908",
  "9909",
  "9912",
  "9916",
  "9917",
  "9921",
  "9954",
  "9955",
  "9956",
  "9958",
] as const;
