// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title Payment means code (UNCL4461)
 * @version D.16B
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4461/
 * @enum
 * @category Peppol Values
 */
export const paymentMeansCodes = {
/**
* Not defined legally enforceable agreement between two or more parties (expressing a contractual right or a right to the payment of money).
*/
"1": "Instrument not defined",
/**
* A credit transaction made through the automated clearing house system.
*/
"2": "Automated clearing house credit",
/**
* A debit transaction made through the automated clearing house system.
*/
"3": "Automated clearing house debit",
/**
* A request to reverse an ACH debit transaction to a demand deposit account.
*/
"4": "ACH demand debit reversal",
/**
* A request to reverse a credit transaction to a demand deposit account.
*/
"5": "ACH demand credit reversal",
/**
* A credit transaction made through the ACH system to a demand deposit account.
*/
"6": "ACH demand credit",
/**
* A debit transaction made through the ACH system to a demand deposit account.
*/
"7": "ACH demand debit",
/**
* Indicates that the bank should hold the payment for collection by the beneficiary or other instructions.
*/
"8": "Hold",
/**
* Indicates that the payment should be made using the national or regional clearing.
*/
"9": "National or regional clearing",
/**
* Payment by currency (including bills and coins) in circulation, including checking account deposits.
*/
"10": "In cash",
/**
* A request to reverse an ACH credit transaction to a savings account.
*/
"11": "ACH savings credit reversal",
/**
* A request to reverse an ACH debit transaction to a savings account.
*/
"12": "ACH savings debit reversal",
/**
* A credit transaction made through the ACH system to a savings account.
*/
"13": "ACH savings credit",
/**
* A debit transaction made through the ACH system to a savings account.
*/
"14": "ACH savings debit",
/**
* A credit entry between two accounts at the same bank branch. Synonym: house credit.
*/
"15": "Bookentry credit",
/**
* A debit entry between two accounts at the same bank branch. Synonym: house debit.
*/
"16": "Bookentry debit",
/**
* A credit transaction made through the ACH system to a demand deposit account using the CCD payment format.
*/
"17": "ACH demand cash concentration/disbursement (CCD) credit",
/**
* A debit transaction made through the ACH system to a demand deposit account using the CCD payment format.
*/
"18": "ACH demand cash concentration/disbursement (CCD) debit",
/**
* A credit transaction made through the ACH system to a demand deposit account using the CTP payment format.
*/
"19": "ACH demand corporate trade payment (CTP) credit",
/**
* Payment by a pre-printed form on which instructions are given to an account holder (a bank or building society) to pay a stated sum to a named recipient.
*/
"20": "Cheque",
/**
* Issue of a banker's draft in payment of the funds.
*/
"21": "Banker's draft",
/**
* Cheque drawn by a bank on itself or its agent. A person who owes money to another buys the draft from a bank for cash and hands it to the creditor who need have no fear that it might be dishonoured.
*/
"22": "Certified banker's draft",
/**
* Payment by a pre-printed form, which has been completed by a financial institution, on which instructions are given to an account holder (a bank or building society) to pay a stated sum to a named recipient.
*/
"23": "Bank cheque (issued by a banking or similar establishment)",
/**
* Bill drawn by the creditor on the debtor but not yet accepted by the debtor.
*/
"24": "Bill of exchange awaiting acceptance",
/**
* Payment by a pre-printed form stamped with the paying bank's certification on which instructions are given to an account holder (a bank or building society) to pay a stated sum to a named recipient .
*/
"25": "Certified cheque",
/**
* Indicates that the cheque is given local to the recipient.
*/
"26": "Local cheque",
/**
* A debit transaction made through the ACH system to a demand deposit account using the CTP payment format.
*/
"27": "ACH demand corporate trade payment (CTP) debit",
/**
* A credit transaction made through the ACH system to a demand deposit account using the CTX payment format.
*/
"28": "ACH demand corporate trade exchange (CTX) credit",
/**
* A debit transaction made through the ACH system to a demand account using the CTX payment format.
*/
"29": "ACH demand corporate trade exchange (CTX) debit",
/**
* Payment by credit movement of funds from one account to another.
*/
"30": "Credit transfer",
/**
* Payment by debit movement of funds from one account to another.
*/
"31": "Debit transfer",
/**
* A credit transaction made through the ACH system to a demand deposit account using the CCD+ payment format.
*/
"32": "ACH demand cash concentration/disbursement plus (CCD+) credit",
/**
* A debit transaction made through the ACH system to a demand deposit account using the CCD+ payment format.
*/
"33": "ACH demand cash concentration/disbursement plus (CCD+) debit",
/**
* A consumer credit transaction made through the ACH system to a demand deposit or savings account.
*/
"34": "ACH prearranged payment and deposit (PPD)",
/**
* A credit transaction made through the ACH system to a demand deposit or savings account.
*/
"35": "ACH savings cash concentration/disbursement (CCD) credit",
/**
* A debit transaction made through the ACH system to a savings account using the CCD payment format.
*/
"36": "ACH savings cash concentration/disbursement (CCD) debit",
/**
* A credit transaction made through the ACH system to a savings account using the CTP payment format.
*/
"37": "ACH savings corporate trade payment (CTP) credit",
/**
* A debit transaction made through the ACH system to a savings account using the CTP payment format.
*/
"38": "ACH savings corporate trade payment (CTP) debit",
/**
* A credit transaction made through the ACH system to a savings account using the CTX payment format.
*/
"39": "ACH savings corporate trade exchange (CTX) credit",
/**
* A debit transaction made through the ACH system to a savings account using the CTX payment format.
*/
"40": "ACH savings corporate trade exchange (CTX) debit",
/**
* A credit transaction made through the ACH system to a savings account using the CCD+ payment format.
*/
"41": "ACH savings cash concentration/disbursement plus (CCD+) credit",
/**
* Payment by an arrangement for settling debts that is operated by the Post Office.
*/
"42": "Payment to bank account",
/**
* A debit transaction made through the ACH system to a savings account using the CCD+ payment format.
*/
"43": "ACH savings cash concentration/disbursement plus (CCD+) debit",
/**
* Bill drawn by the creditor on the debtor and accepted by the debtor.
*/
"44": "Accepted bill of exchange",
/**
* A referenced credit transfer initiated through home- banking.
*/
"45": "Referenced home-banking credit transfer",
/**
* A debit transfer via interbank means.
*/
"46": "Interbank debit transfer",
/**
* A debit transfer initiated through home-banking.
*/
"47": "Home-banking debit transfer",
/**
* Payment by means of a card issued by a bank or other financial institution.
*/
"48": "Bank card",
/**
* The amount is to be, or has been, directly debited to the customer's bank account.
*/
"49": "Direct debit",
/**
* A method for the transmission of funds through the postal system rather than through the banking system.
*/
"50": "Payment by postgiro",
/**
* Banking Standards) - Option A A French standard procedure that allows a debtor to pay an amount due to a creditor. The creditor will forward it to its bank, which will collect the money on the bank account of the debtor.
*/
"51": "FR, norme 6 97-Telereglement CFONB (French Organisation for",
/**
* Payment order which requires guaranteed processing by the most appropriate means to ensure it occurs on the requested execution date, provided that it is issued to the ordered bank before the agreed cut-off time.
*/
"52": "Urgent commercial payment",
/**
* Payment order or transfer which must be executed, by the most appropriate means, as urgently as possible and before urgent commercial payments.
*/
"53": "Urgent Treasury Payment",
/**
* Payment made by means of credit card.
*/
"54": "Credit card",
/**
* Payment made by means of debit card.
*/
"55": "Debit card",
/**
* Payment will be, or has been, made by bankgiro.
*/
"56": "Bankgiro",
/**
* The payment means have been previously agreed between seller and buyer and thus are not stated again.
*/
"57": "Standing agreement",
/**
* Credit transfer inside the Single Euro Payment Area (SEPA) system.
*/
"58": "SEPA credit transfer",
/**
* Direct debit inside the Single Euro Payment Area (SEPA) system.
*/
"59": "SEPA direct debit",
/**
* Payment by an unconditional promise in writing made by one person to another, signed by the maker, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"60": "Promissory note",
/**
* Payment by an unconditional promise in writing made by the debtor to another person, signed by the debtor, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"61": "Promissory note signed by the debtor",
/**
* Payment by an unconditional promise in writing made by the debtor to another person, signed by the debtor and endorsed by a bank, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"62": "Promissory note signed by the debtor and endorsed by a bank",
/**
* Payment by an unconditional promise in writing made by the debtor to another person, signed by the debtor and endorsed by a third party, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"63": "Promissory note signed by the debtor and endorsed by a third party",
/**
* Payment by an unconditional promise in writing made by the bank to another person, signed by the bank, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"64": "Promissory note signed by a bank",
/**
* Payment by an unconditional promise in writing made by the bank to another person, signed by the bank and endorsed by another bank, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"65": "Promissory note signed by a bank and endorsed by another bank",
/**
* Payment by an unconditional promise in writing made by a third party to another person, signed by the third party, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"66": "Promissory note signed by a third party",
/**
* Payment by an unconditional promise in writing made by a third party to another person, signed by the third party and endorsed by a bank, engaging to pay on demand or at a fixed or determinable future time a sum certain in money, to order or to bearer.
*/
"67": "Promissory note signed by a third party and endorsed by a bank",
/**
* Payment will be made or has been made by an online payment service.
*/
"68": "Online payment service",
/**
* Bill drawn by the creditor on the debtor.
*/
"70": "Bill drawn by the creditor on the debtor",
/**
* Bill drawn by the creditor on a bank.
*/
"74": "Bill drawn by the creditor on a bank",
/**
* Bill drawn by the creditor, endorsed by another bank.
*/
"75": "Bill drawn by the creditor, endorsed by another bank",
/**
* Bill drawn by the creditor on a bank and endorsed by a third party.
*/
"76": "Bill drawn by the creditor on a bank and endorsed by a third party",
/**
* Bill drawn by the creditor on a third party.
*/
"77": "Bill drawn by the creditor on a third party",
/**
* Bill drawn by creditor on third party, accepted and endorsed by bank.
*/
"78": "Bill drawn by creditor on third party, accepted and endorsed by bank",
/**
* Issue a bankers draft not endorsable.
*/
"91": "Not transferable banker's draft",
/**
* Issue a cheque not endorsable in payment of the funds.
*/
"92": "Not transferable local cheque",
/**
* Ordering customer tells the bank to use the payment system 'Reference giro'. Used in the Finnish national banking system.
*/
"93": "Reference giro",
/**
* Ordering customer tells the bank to use the bank service 'Urgent Giro' when transferring the payment. Used in Finnish national banking system.
*/
"94": "Urgent giro",
/**
* Ordering customer tells the ordering bank to use the bank service 'Free Format Giro' when transferring the payment. Used in Finnish national banking system.
*/
"95": "Free format giro",
/**
* If the requested method for payment was or could not be used, this code indicates that.
*/
"96": "Requested method for payment was not used",
/**
* Amounts which two partners owe to each other to be compensated in order to avoid useless payments.
*/
"97": "Clearing between partners",
/**
* An electronically recorded monetary claim is a claim that is separate from the underlying debt that gave rise to its accrual.Therefore, even if an electronically recorded monetary claim is accrued as a means of payment of the underlying debt, the underlying debt will not be extinguished as a matter of course.
*/
"98": "JP, Electronically Recorded Monetary Claims",
/**
* A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to the code list.
*/
"ZZZ": "Mutually defined",
"69": "Transfer Advice",

} as const;

/**
 * Keys of {@link paymentMeansCodes}.
 */
export type paymentMeansCodesKey = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "20" | "21" | "22" | "23" | "24" | "25" | "26" | "27" | "28" | "29" | "30" | "31" | "32" | "33" | "34" | "35" | "36" | "37" | "38" | "39" | "40" | "41" | "42" | "43" | "44" | "45" | "46" | "47" | "48" | "49" | "50" | "51" | "52" | "53" | "54" | "55" | "56" | "57" | "58" | "59" | "60" | "61" | "62" | "63" | "64" | "65" | "66" | "67" | "68" | "70" | "74" | "75" | "76" | "77" | "78" | "91" | "92" | "93" | "94" | "95" | "96" | "97" | "98" | "ZZZ" | "69";
export const paymentMeansCodesKeys = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "70",
  "74",
  "75",
  "76",
  "77",
  "78",
  "91",
  "92",
  "93",
  "94",
  "95",
  "96",
  "97",
  "98",
  "ZZZ",
  "69",
] as const satisfies readonly [paymentMeansCodesKey, ...paymentMeansCodesKey[]];
