// oxlint-disable
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @version D.16B
 *
 * @category Peppol Values
 *
 * @title VAT date code (UNCL2005 subset)
 *
 * @enum
 *
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL2005/
 */
export const vatDateCodes = { '3': 'Invoice document issue date time', '35': 'Delivery date/time, actual', '432': 'Paid to date' };

/**
 * @description Keys of {@link vatDateCodes}.
 */
export const vatDateCodesKeys = ['3', '35', '432'] as const;
