// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by `scripts/values.ts`

/**
 * @title VAT date code (UNCL2005 subset)
 * @version D.16B
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL2005/
 * @enum
 * @category Peppol Values
 */
export const vatDateCodes = {
"3": "Invoice document issue date time",
"35": "Delivery date/time, actual",
"432": "Paid to date",

} as const;

/**
 * Keys of {@link vatDateCodes}.
 */
export type vatDateCodesKey = "3" | "35" | "432";
export const vatDateCodesKeys = [
  "3",
  "35",
  "432",
] as const satisfies readonly [vatDateCodesKey, ...vatDateCodesKey[]];
