import { $ } from 'bun';
import { promises as fs } from 'node:fs';
import path from 'node:path';

import { generateKeyDeclarations } from './generate-key-declarations';

/**
 * @description Generate values and validation rules from https://github.com/OpenPEPPOL/peppol-bis-invoice-3.
 */
export async function generateFromPeppol(valuePath: string) {
  const peppolTempDir = (await $`mktemp -d /tmp/peppol-XXXXXX`.text()).trim();
  const peppolTempDirPoAcc = (await $`mktemp -d /tmp/peppol-XXXXXX`.text()).trim();

  function generateFileContent({
    variableName,
    content,
    keys,
    version,
    identifier,
    title,
  }: {
    variableName: string;
    content: string;
    keys: ReadonlyArray<string>;
    version?: string;
    identifier: string;
    title: string;
  }): string {
    return `// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @title ${title}
${version ? ` * @version ${version}` : ''}
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/${identifier}/
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${content}
};

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, variableName: variableName })}
`;
  }

  /**
   * @description Generate the values from https://github.com/OpenPEPPOL/peppol-bis-invoice-3.
   */
  async function generateValues() {
    console.log('Cloning PEPPOL BIS Invoice 3 repository to', peppolTempDir);
    await $`git clone --depth 1 https://github.com/OpenPEPPOL/peppol-bis-invoice-3 ${peppolTempDir}`.quiet();

    console.log('Cloning PEPPOL poaccc 3 repository to', peppolTempDirPoAcc);
    await $`git clone --depth 1 https://github.com/OpenPEPPOL/poacc-upgrade-3.git ${peppolTempDirPoAcc}`.quiet();

    console.log('Creating value path at', valuePath);
    await $`mkdir -p ${valuePath}`.quiet();

    console.log('--- Starting to process value files ---');
    const generationList = [
      [`${peppolTempDir}/structure/codelist/ISO3166-1_Alpha2.xml`, 'country-code.generated.ts', 'countryCodes'],
      [`${peppolTempDir}/structure/codelist/ISO4217_2015.xml`, 'currency-code.generated.ts', 'currencyCodes'],
      [`${peppolTempDir}/structure/codelist/MimeCode.xml`, 'mime-codes.generated.ts', 'mimeCodes'],
      // [`${peppolTempDir}/structure/codelist/SEPA.xml`, 'sepa-codes.generated.ts', 'sepaCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL1001-cn.xml`, 'credit-notes-type-codes.generated.ts', 'creditNoteTypeCodes', 'documentTypeCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL1001-inv.xml`, 'invoice-type-codes.generated.ts', 'invoiceTypeCodes', 'documentTypeCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL1153.xml`, 'additional-document-reference-codes.generated.ts', 'additionalDocumentReferenceCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL2005.xml`, 'vat-dates.generated.ts', 'vatDateCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL4461.xml`, 'payment-means-codes.generated.ts', 'paymentMeansCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL5189.xml`, 'allowance-charge-reason-codes.generated.ts', 'allowanceChargeReasonCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL5305.xml`, 'duty-tax-fee-categories.generated.ts', 'dutyTaxFeeCategories'],
      [`${peppolTempDir}/structure/codelist/UNCL7143.xml`, 'item-classification-code.generated.ts', 'itemClassificationCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL7161.xml`, 'charge-reason-codes.generated.ts', 'chargeReasonCodes'],
      [`${peppolTempDir}/structure/codelist/UNECERec20-11e.xml`, 'quantity-unit-codes.generated.ts', 'quantityUnitCodes'],
      [`${peppolTempDir}/structure/codelist/VATEX.xml`, 'vatex-codes.generated.ts', 'vatexCodes'],
      [`${peppolTempDir}/structure/codelist/eas.xml`, 'eas-codes.generated.ts', 'electronicAddressCodes'],
      [`${peppolTempDir}/structure/codelist/icd.xml`, 'icd-codes.generated.ts', 'icdCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/UNCL1001.xml`, 'document-type-codes.generated.ts', 'documentTypeCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/UNCL4343.xml`, 'application-response-type-codes.generated.ts', 'applicationResponseTypeCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/UNCL4343-T111.xml`, 'invoice-status-codes.generated.ts', 'invoiceStatusCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/OPStatusAction.xml`, 'op-status-action.generated.ts', 'opStatusAction'],
      [`${peppolTempDirPoAcc}/structure/codelist/OPStatusReason.xml`, 'op-status-reason.generated.ts', 'opStatusReason'],
    ] as const;

    for (const [peppolFileName, outputFileName, variableName] of generationList) {
      console.log('Processing', peppolFileName, '->', outputFileName);
      const title = (await $`cat ${peppolFileName} | xq ".CodeList.Title"`.text()).replaceAll('"', '').trim();
      const identifier = (await $`cat ${peppolFileName} | xq ".CodeList.Identifier"`.text()).replaceAll('"', '').trim();
      const version = (await $`cat ${peppolFileName} | xq ".CodeList.Version"`.text()).replaceAll('"', '').trim();
      const keys = (await $`cat ${peppolFileName} | xq ".CodeList.Code | map(.Id | tostring)"`.json()) as Array<string>;
      const content =
        await $`cat ${peppolFileName} | xq ".CodeList.Code[]" | jq -r '(if has("Description") and .Description != null then "/**\n* " + (.Description | sub("\n"; ""; "g") | sub(" {2,}"; " "; "g")) + "\n*/\n" else "" end) + "\"" + .Id + "\": \"" + (.Name | sub("\n"; ""; "g") | sub("\""; ""; "g") | sub(" {2,}"; " "; "g")) + "\","'`.text();

      console.log('Writing to', outputFileName);
      await fs.writeFile(path.join(valuePath, outputFileName), generateFileContent({ content, identifier, keys, title, variableName, version }));
      console.log('Finished writing', outputFileName);
    }

    console.log('--- All value files processed ---');
  }

  try {
    await generateValues();
  } finally {
    console.log('Cleaning up temporary directory', peppolTempDirPoAcc);
    await $`rm -rf ${peppolTempDirPoAcc}`.quiet();
    console.log('Cleaning up temporary directory', peppolTempDir);
    await $`rm -rf ${peppolTempDir}`.quiet();
  }
}
