// fallow-ignore-file security-sink
// Offline codegen script: paths are repo-relative constants, no untrusted input.
import { String } from 'effect';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import pc from 'picocolors';

import { generateKeyDeclarations } from './generate-key-declarations';
import { Git } from './git';
/**
 * @description The latest version of the document types.\
 * Since they release process is kinda scary, I keep it raw here and update manually.\
 * (They don't bother create any github release)
 */
const version = 'v9.7';

async function generateDocumentTypes(valuePath: string, publicationPath: string) {
  console.log(`Processing ${pc.blueBright('document types')}`);
  const sourceFileName = `Peppol Code Lists - Document types ${version}.json`;
  const generatedFileName = 'document-type.generated.ts';
  const variableName = 'documentTypes';
  const documentTypesContent = JSON.parse(await fs.readFile(path.join(publicationPath, sourceFileName), 'utf-8')) as {
    version: string;
    values: Array<Record<string, string>>;
  };

  const grouped = documentTypesContent.values.reduce<Record<string, Array<Record<string, string>>>>((prev, curr) => {
    (prev[curr['scheme']!] ??= []).push(curr);
    return prev;
  }, {});
  const tableKeys = Object.keys(grouped);

  await fs.writeFile(
    path.join(valuePath, generatedFileName),
    `// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

export const ${variableName}Table = {
${Object.entries(grouped)
  .map(([key, value]) => `  "${key}": [ ${value.map(v => `"${v['value']}"`).join(', ')} ]`)
  .join(',\n')}
};

${generateKeyDeclarations({ keys: tableKeys, keysName: `${variableName}TableKeys`, variableName: `${variableName}Table` })}

export const ${variableName}Scheme = [
${tableKeys.map(key => `  "${key}",`).join('\n')}
];


export const ${variableName}ProcessIds = {
${Object.entries(grouped)
  .map(([key, value]) => value.map(v => `"${key}::${v['value']}": ${JSON.stringify(v['process-ids'])}`).join(',\n'))
  .join(',\n')}
};

export const ${variableName}List = [
${Object.entries(grouped)
  .flatMap(([key, value]) => value.map(v => `"${key}::${v['value']}"`).join(',\n'))
  .join(',\n')}
];

/**
 * The list of elements that are deprecated.
 */
export const deprecated${String.capitalize(variableName)} = [
${documentTypesContent.values
  .filter(value => value['state'] !== 'active')
  .map(value => `  "${value['value']}",`)
  .join('\n')}
];
`
  );
}

async function generateParticipantIdentifierSchemes(valuePath: string, publicationPath: string) {
  console.log(`Processing ${pc.blueBright('participant identifier schemes')}`);

  const sourceFileName = `Peppol Code Lists - Participant identifier schemes ${version}.json`;
  const generatedFileName = 'participant-identifier-schemes.generated.ts';
  const variableName = 'participantIdentifierSchemes';
  const documentTypesContent = JSON.parse(await fs.readFile(path.join(publicationPath, sourceFileName), 'utf-8')) as {
    version: string;
    values: Array<Record<string, string | undefined>>;
  };
  const keys = documentTypesContent.values.map(value => value['iso6523']).filter((value): value is string => Boolean(value));

  await fs.writeFile(
    path.join(valuePath, generatedFileName),
    `// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @title Peppol Participant Identifier Schemes
 * @version ${documentTypesContent.version}
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${documentTypesContent.values
  .map(value => {
    const examples = value['examples']
      ? `\n* @example \n* ${value['examples']
          ?.split('\n')
          .map(ex => `\`${ex.trim()}\``)
          .join('\n* ')}`
      : '';

    const validations = value['validation-rules']
      ? `\n* @validation \n* ${value['validation-rules']
          .split('\n')
          .map(rule => {
            const r = rule.trim();
            if (r.startsWith('RegEx: ')) {
              return `\`\`\`regex\n* ${r.slice(7)}\n* \`\`\``;
            }
            return r;
          })
          .join('\n* ')}`
      : '';

    return `/**
* @name \`${value['scheme-name']?.replace('\n', ' ')}\`
* @country \`${value['country']}\`
* @since ${value['initial-release']}${value['state'] !== 'active' ? '\n* @deprecated' : ''}${examples}${validations}
*/
"${value['iso6523']}": "${value['schemeid']}",`;
  })
  .join('\n')}
};

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, variableName: variableName })}

export const ${variableName}Validations = {
${documentTypesContent.values
  .map(value => {
    const validations = value['validation-rules']
      ? value['validation-rules']
          .split('\n')
          .filter(rule => rule.trim().startsWith('RegEx: '))
          .map(rule => {
            const r = rule.trim();
            return `/${r.slice(7)}/g`;
          })
          .join(', ')
      : '';

    return `"${value['iso6523']}": ${String.isEmpty(validations) ? 'undefined' : `[${validations}]`},`;
  })
  .join('\n')}
}

/**
 * The list of elements that are deprecated.
 */
export const deprecated${String.capitalize(variableName)} = [
${documentTypesContent.values
  .filter(value => value['state'] !== 'active')
  .map(value => `  "${value['iso6523']}",`)
  .join('\n')}
];
`
  );
}

async function generateProcess(valuePath: string, publicationPath: string) {
  console.log(`Processing ${pc.blueBright('process schemes')}`);
  const sourceFileName = `Peppol Code Lists - Processes ${version}.json`;
  const generatedFileName = 'processes.generated.ts';
  const variableName = 'processes';

  const documentTypesContent = JSON.parse(await fs.readFile(path.join(publicationPath, sourceFileName), 'utf-8')) as {
    version: string;
    values: Array<Record<string, string | undefined>>;
  };

  const grouped = documentTypesContent.values.reduce<Record<string, Array<Record<string, string | undefined>>>>((prev, curr) => {
    (prev[curr['scheme']!] ??= []).push(curr);
    return prev;
  }, {});
  const keys = Object.keys(grouped);

  await fs.writeFile(
    path.join(valuePath, generatedFileName),
    `// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @title Peppol Participant Identifier Schemes
 * @version ${documentTypesContent.version}
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${Object.entries(grouped)
  .map(([key, value]) => `"${key}": [${value.map(value => JSON.stringify(value['value'])).join(',')}]`)
  .join(',\n')}
};

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, variableName: variableName })}

export const ${variableName}Scheme = [
${keys.map(key => `  "${key}",`).join('\n')}
];

export const ${variableName}List = [
${Object.entries(grouped)
  .flatMap(([key, value]) => value.map(v => `"${key}::${v['value']}"`).join(',\n'))
  .join(',\n')}
];

/**
 * The list of elements that are deprecated.
 */
export const deprecated${String.capitalize(variableName)} = [
${documentTypesContent.values
  .filter(value => value['state'] !== 'active')
  .map(value => `  "${value['value']}",`)
  .join('\n')}
];
`
  );
}

export async function generateEdec(valuePath: string) {
  await using edecTempDir = await fs.mkdtempDisposable('/tmp/edec-XXXXXX');

  const edecRepo = 'https://github.com/OpenPEPPOL/edec-codelists.git';
  console.log(`Cloning edec code list (${pc.dim(edecRepo)}) repository to ${pc.yellow(edecTempDir.path)}`);
  await Git.clone(edecRepo, edecTempDir.path, { '--depth': 1 });

  console.log('Creating value folder at', pc.yellow(valuePath));
  await fs.mkdir(valuePath, { recursive: true });

  console.log(pc.green('--- Starting to process edec values files ---'));
  const publicationPath = path.join(edecTempDir.path, 'publication', version);

  // const generationList = [
  //   [`Peppol Code Lists - SPIS Use Case ${version}.json`, 'spi-use-cases.generated.ts', 'spiUseCases'],
  //   [`Peppol Code Lists - Transport profiles ${version}.json`, 'spi-use-cases.generated.ts', 'spiUseCases'],
  // ];

  await generateDocumentTypes(valuePath, publicationPath);
  await generateParticipantIdentifierSchemes(valuePath, publicationPath);
  await generateProcess(valuePath, publicationPath);

  console.log(pc.green('--- All edec value files processed ---'));
}
