import { String } from 'effect';
import { XMLParser } from 'fast-xml-parser';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import pc from 'picocolors';

import { generateKeyDeclarations } from './generate-key-declarations';
import { Git } from './git';

const typescript = String.String.raw;
const xmlParser = new XMLParser({ removeNSPrefix: true, trimValues: true });
const assetsPath = path.join(import.meta.dirname, '..', '..', 'assets');

function normalizeString(str: string): string {
  return str
    .replaceAll('\n', '')
    .replaceAll(/\s{2,}/g, ' ')
    .trim();
}

function generateFileContent({
  variableName,
  content,
  keys,
  version,
  identifier,
  title,
}: {
  variableName: string;
  content: string;
  keys: ReadonlyArray<string | number>;
  version: string | number | undefined;
  identifier: string;
  title: string;
}): string {
  return typescript`// oxlint-disable
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @title ${title}
${version ? ` * @version ${version}` : ''}
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/${identifier}/
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${content}
};

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, variableName: variableName })}
`;
}

/**
 * @description Generate values and validation rules from https://github.com/OpenPEPPOL/peppol-bis-invoice-3.
 */
export async function generateFromPeppol(valuePath: string) {
  await using peppolTempDir = await fs.mkdtempDisposable('/tmp/peppol-bis-XXXXXX');
  await using peppolTempDirPoAcc = await fs.mkdtempDisposable('/tmp/peppol-poacc-XXXXXX');

  /**
   * @description Generate the values from https://github.com/OpenPEPPOL/peppol-bis-invoice-3.
   */
  async function generateValues() {
    const bisRepo = 'https://github.com/OpenPEPPOL/peppol-bis-invoice-3.git';
    console.log(`Cloning PEPPOL BIS Invoice 3 (${pc.dim(bisRepo)}) repository to ${pc.yellow(peppolTempDir.path)}`);
    await Git.clone(bisRepo, peppolTempDir.path, { '--depth': 1 });

    const poaccRepo = 'https://github.com/OpenPEPPOL/poacc-upgrade-3.git';
    console.log(`Cloning PEPPOL poacc 3 repository (${pc.dim(poaccRepo)}) repository to ${pc.yellow(peppolTempDirPoAcc.path)}`);
    await Git.clone(poaccRepo, peppolTempDirPoAcc.path, { '--depth': 1 });

    console.log('Creating value folder at', pc.yellow(valuePath));
    await fs.mkdir(valuePath, { recursive: true });

    console.log(pc.green('--- Starting to process value files ---'));
    const generationList = [
      [`${peppolTempDir.path}/structure/codelist/ISO3166-1_Alpha2.xml`, 'country-code.generated.ts', 'countryCodes'],
      [`${peppolTempDir.path}/structure/codelist/ISO4217_2015.xml`, 'currency-code.generated.ts', 'currencyCodes'],
      [`${peppolTempDir.path}/structure/codelist/MimeCode.xml`, 'mime-codes.generated.ts', 'mimeCodes'],
      // [`${peppolTempDir.path}/structure/codelist/SEPA.xml`, 'sepa-codes.generated.ts', 'sepaCodes'],
      [
        `${peppolTempDir.path}/structure/codelist/UNCL1001-cn.xml`,
        'credit-notes-type-codes.generated.ts',
        'creditNoteTypeCodes',
        'documentTypeCodes',
      ],
      [`${peppolTempDir.path}/structure/codelist/UNCL1001-inv.xml`, 'invoice-type-codes.generated.ts', 'invoiceTypeCodes', 'documentTypeCodes'],
      [
        `${peppolTempDir.path}/structure/codelist/UNCL1153.xml`,
        'additional-document-reference-codes.generated.ts',
        'additionalDocumentReferenceCodes',
      ],
      [`${peppolTempDir.path}/structure/codelist/UNCL2005.xml`, 'vat-dates.generated.ts', 'vatDateCodes'],
      [`${peppolTempDir.path}/structure/codelist/UNCL4461.xml`, 'payment-means-codes.generated.ts', 'paymentMeansCodes'],
      [`${peppolTempDir.path}/structure/codelist/UNCL5189.xml`, 'allowance-charge-reason-codes.generated.ts', 'allowanceChargeReasonCodes'],
      [`${peppolTempDir.path}/structure/codelist/UNCL5305.xml`, 'duty-tax-fee-categories.generated.ts', 'dutyTaxFeeCategories'],
      [`${peppolTempDir.path}/structure/codelist/UNCL7143.xml`, 'item-classification-code.generated.ts', 'itemClassificationCodes'],
      [`${peppolTempDir.path}/structure/codelist/UNCL7161.xml`, 'charge-reason-codes.generated.ts', 'chargeReasonCodes'],
      [`${peppolTempDir.path}/structure/codelist/UNECERec20-11e.xml`, 'quantity-unit-codes.generated.ts', 'quantityUnitCodes'],
      [`${peppolTempDir.path}/structure/codelist/VATEX.xml`, 'vatex-codes.generated.ts', 'vatexCodes'],
      [`${peppolTempDir.path}/structure/codelist/eas.xml`, 'eas-codes.generated.ts', 'electronicAddressCodes'],
      [`${peppolTempDir.path}/structure/codelist/icd.xml`, 'icd-codes.generated.ts', 'icdCodes'],
      [`${peppolTempDirPoAcc.path}/structure/codelist/UNCL1001.xml`, 'document-type-codes.generated.ts', 'documentTypeCodes'],
      [`${peppolTempDirPoAcc.path}/structure/codelist/UNCL4343.xml`, 'application-response-type-codes.generated.ts', 'applicationResponseTypeCodes'],
      [`${peppolTempDirPoAcc.path}/structure/codelist/UNCL4343-T111.xml`, 'invoice-status-codes.generated.ts', 'invoiceStatusCodes'],
      [`${peppolTempDirPoAcc.path}/structure/codelist/OPStatusAction.xml`, 'op-status-action.generated.ts', 'opStatusAction'],
      [`${peppolTempDirPoAcc.path}/structure/codelist/OPStatusReason.xml`, 'op-status-reason.generated.ts', 'opStatusReason'],
    ] as const;

    let translationsKeys: Record<string, Record<string, { text: string; description: string }>> = {};
    for (const [peppolFileName, outputFileName, variableName, groupName] of generationList) {
      console.log('Processing', pc.yellow(pc.italic(peppolFileName)), '->', pc.yellow(pc.italic(outputFileName)));
      const peppolFileContent: {
        CodeList: {
          Title: string;
          Identifier: string;
          Version: string | number | undefined;
          Code: Array<{ Id: string | number; Name: string; Description?: string }>;
        };
      } = xmlParser.parse(await fs.readFile(peppolFileName, { encoding: 'utf-8' }));

      const title = peppolFileContent['CodeList']['Title'];
      const identifier = peppolFileContent['CodeList']['Identifier'];
      const version = peppolFileContent['CodeList']['Version'];
      const keys = peppolFileContent['CodeList']['Code'].map(code => code.Id);
      const content = peppolFileContent['CodeList']['Code'].reduce((prev, code) => {
        const content = `"${code.Id}": "${normalizeString(code.Name).replaceAll('"', '\\"')}",\n`;
        if (code.Description) {
          return `${prev}/**\n* ${normalizeString(code.Description)}\n*/\n${content}`;
        }
        return `${prev}\n${content}`;
      }, '');

      translationsKeys[groupName ?? variableName] = {
        ...translationsKeys[groupName ?? variableName],
        ...keys.reduce(
          (prev, key) => {
            const keyLower = String.snakeCase(String.toLowerCase(`${key}`));
            const group = String.snakeCase(groupName ?? variableName);
            prev[key] = { text: `peppol_${group}_${keyLower}_text`, description: `peppol_${group}_${keyLower}_description` };
            return prev;
          },
          {} as Record<string | number, { text: string; description: string }>
        ),
      };

      console.log('Writing to', pc.yellow(outputFileName));
      await fs.writeFile(path.join(valuePath, outputFileName), generateFileContent({ content, identifier, keys, title, variableName, version }));
      console.log('Finished writing', pc.yellow(outputFileName));
    }
    console.log(pc.green('--- All value files processed ---'));

    const translationFile = path.join(assetsPath, 'translations.json');
    console.log('Writing translations to', pc.yellow(translationFile));
    await fs.writeFile(
      translationFile,
      JSON.stringify(Object.fromEntries(Object.entries(translationsKeys).toSorted(([aKey], [bKey]) => aKey.localeCompare(bKey))), null, 2)
    );
    console.log('Finished writing translations', pc.yellow(translationFile));
  }

  await generateValues();
}
