import { recommended } from '@effect/tsgo/oxlint-presets';
import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: { correctness: 'error' },
  env: { browser: true, builtin: true, node: true, vitest: true },
  extends: [recommended],
  ignorePatterns: ['**/dist', '**/node_modules', '**/coverage'],
  overrides: [
    { files: ['**/*.spec.ts'], rules: { 'typescript/no-explicit-any': 'off' } },
    { files: ['**/{effect,schemas,decoders}/**/*.ts'], rules: { 'typescript/no-redundant-type-constituents': 'off', 'sort-keys': 'off' } },
    {
      files: [
        './src/index.ts',
        './src/schemas.ts',
        './src/peppol-validations/index.ts',
        './src/values.ts',
        './src/constants/index.ts',
        './src/effect/index.ts',
        './src/effect/values/index.ts',
        './src/effect/utils/index.ts',
      ],
      rules: { 'oxc/no-barrel-file': 'off', 'typescript/consistent-type-exports': 'off' },
    },
    { files: ['**/scripts/**/*.ts', '**/*.spec.ts'], rules: { 'effecttsgo/node-builtin-import': 'allow' } },
  ],
  plugins: ['oxc', 'typescript', 'unicorn', 'import', 'vitest', 'node', 'promise'],
  rules: {
    'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
    'effecttsgo/any-unknown-in-error-context': 'warn',
    'effecttsgo/async-function': 'off',
    'effecttsgo/catch-to-or-else-succeed': 'warn',
    'effecttsgo/crypto-random-uuid': 'off',
    'effecttsgo/crypto-random-uuid-in-effect': 'warn',
    'effecttsgo/extends-native-error': 'warn',
    'effecttsgo/global-console': 'off',
    'effecttsgo/global-console-in-effect': 'warn',
    'effecttsgo/global-date': 'off',
    'effecttsgo/global-date-in-effect': 'warn',
    'effecttsgo/global-fetch': 'off',
    'effecttsgo/global-fetch-in-effect': 'warn',
    'effecttsgo/global-random': 'off',
    'effecttsgo/global-random-in-effect': 'warn',
    'effecttsgo/global-timers': 'off',
    'effecttsgo/global-timers-in-effect': 'warn',
    'effecttsgo/instance-of-schema': 'off',
    'effecttsgo/leaking-requirements': 'error',
    'effecttsgo/new-promise': 'off',
    'effecttsgo/node-builtin-import': 'warn',
    'effecttsgo/prefer-schema-over-json': 'warn',
    'effecttsgo/process-env': 'off',
    'effecttsgo/process-env-in-effect': 'warn',
    'effecttsgo/redundant-schema-tag-identifier': 'allow', // NOTE: this rule is allowed for now to reduce noise
    'effecttsgo/unnecessary-fail-yieldable-error': 'warn',
    'effecttsgo/unsafe-effect-type-assertion': 'warn',
    'import/consistent-type-specifier-style': 'error',
    'import/newline-after-import': 'warn',
    'import/no-relative-parent-imports': 'error',
    'import/unambiguous': 'warn',
    'no-restricted-imports': [
      'error',
      { allowTypeImports: false, name: '#/index', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/schema', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/values', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/peppol-validations', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/constants', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/schematron', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/effect', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/effect/values', message: 'Please import the specific file instead of the application module export' },
      { allowTypeImports: false, name: '#/effect/utils', message: 'Please import the specific file instead of the application module export' },
    ],
    'oxc/no-barrel-file': 'warn',
    'prefer-template': 'warn',
    'require-yield': 'off',
    'sort-imports': 'off',
    'sort-keys': ['warn', 'asc', { minKeys: 5, natural: true }],
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/array-type': ['error', { default: 'generic', readonly: 'generic' }],
    'typescript/consistent-type-exports': 'error',
    'typescript/consistent-type-imports': ['error', { fixStyle: 'separate-type-imports', disallowTypeAnnotations: false }],
    'typescript/no-explicit-any': 'error',
    'typescript/no-misused-spread': 'off',
    'typescript/no-unnecessary-boolean-literal-compare': 'warn',
    'typescript/no-unnecessary-type-arguments': 'warn',
    'typescript/no-unnecessary-type-constraint': 'warn',
    'typescript/no-unnecessary-type-conversion': 'warn',
    'typescript/prefer-nullish-coalescing': 'off',
    'typescript/restrict-template-expressions': ['warn', { allowNever: true }],
    'vitest/no-conditional-expect': 'off',
    'vitest/no-standalone-expect': 'off',
    'vitest/require-to-throw-message': 'off',
    yoda: 'warn',
  },
});
