allowBuilds:
  cpu-features: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
overrides:
  '@endevops/builder': link:../effect-xml/packages/builder
  '@endevops/common-xml': link:../effect-xml/packages/common-xml
  '@endevops/effect-xml': link:../effect-xml
  '@endevops/effect-xml-codec': link:../effect-xml/packages/effect-xml-codec
  '@endevops/parser': link:../effect-xml/packages/parser
