overrides:
  vite@*: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest@*: "catalog:"
catalog:
  vitest: 5.0.1
  vite-plus: 1.0.0
  "@vitest/coverage-v8": 5.0.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  cpu-features: true
  protobufjs: true
  ssh2: true
minimumReleaseAgeExclude:
  - effect@4.0.0
  - "@effect/platform-node@4.0.0"
  - "@effect/platform-node-shared@4.0.0"
  - "@effect/vitest@4.0.0"
  - "@endevops/common-xml@0.0.1 || 1.0.0-effect.2"
  - "@endevops/effect-codec-xml@0.0.1"
