import { Schema } from 'effect';
import { assert, describe, expect, it } from 'vite-plus/test';

import { serializedOrder } from '#/test/xsd-sequence.ts';

/**
 * @description UBL 2.1 element order for every schema with more than one element field, keyed by `<module>#<export>`. Derived from the UBL 2.1 XSD sequences
 * (Invoice, CreditNote, ApplicationResponse and CommonAggregateComponents) restricted to the elements each schema declares. A schema whose fields are
 * not in this order serializes an invalid document, so these assertions pin serialization to the XSD sequence.
 *
 * @remarks
 *   Attribute (`xmlAttribute`) and character-data (`xmlValue`) fields are not elements and do not appear here.
 */
const expected: Record<string, ReadonlyArray<string>> = {
  './fields/peppol-additional-document-reference-schema.ts#PeppolAdditionalDocumentReference': [
    'cbc:ID',
    'cbc:DocumentTypeCode',
    'cbc:DocumentDescription',
    'cac:Attachment',
  ],
  './fields/peppol-additional-document-reference-schema.ts#PeppolAttachment': ['cbc:EmbeddedDocumentBinaryObject', 'cac:ExternalReference'],
  './fields/peppol-address-schema.ts#PeppolAddress': [
    'cbc:StreetName',
    'cbc:AdditionalStreetName',
    'cbc:CityName',
    'cbc:PostalZone',
    'cbc:CountrySubentity',
    'cac:AddressLine',
    'cac:Country',
  ],
  './fields/peppol-allowance-charge-schema.ts#PeppolAllowance': [
    'cbc:ChargeIndicator',
    'cbc:AllowanceChargeReasonCode',
    'cbc:AllowanceChargeReason',
    'cbc:MultiplierFactorNumeric',
    'cbc:Amount',
    'cbc:BaseAmount',
    'cac:TaxCategory',
  ],
  './fields/peppol-allowance-charge-schema.ts#PeppolCharge': [
    'cbc:ChargeIndicator',
    'cbc:AllowanceChargeReasonCode',
    'cbc:AllowanceChargeReason',
    'cbc:MultiplierFactorNumeric',
    'cbc:Amount',
    'cbc:BaseAmount',
    'cac:TaxCategory',
  ],
  './fields/peppol-billing-reference-schema.ts#PeppolInvoiceDocumentReference': ['cbc:ID', 'cbc:IssueDate'],
  './fields/peppol-contact-schema.ts#PeppolContact': ['cbc:Name', 'cbc:Telephone', 'cbc:ElectronicMail'],
  './fields/peppol-credit-note-line-schema.ts#PeppolCreditNoteLine': [
    'cbc:ID',
    'cbc:Note',
    'cbc:CreditedQuantity',
    'cbc:LineExtensionAmount',
    'cbc:AccountingCost',
    'cac:InvoicePeriod',
    'cac:OrderLineReference',
    'cac:DocumentReference',
    'cac:AllowanceCharge',
    'cac:Item',
    'cac:Price',
  ],
  './fields/peppol-delivery-schema.ts#PeppolDelivery': ['cbc:ActualDeliveryDate', 'cac:DeliveryLocation', 'cac:DeliveryParty'],
  './fields/peppol-delivery-schema.ts#PeppolDeliveryLocation': ['cbc:ID', 'cac:Address'],
  './fields/peppol-invoice-line-period-schema.ts#PeppolInvoiceLinePeriod': ['cbc:StartDate', 'cbc:EndDate'],
  './fields/peppol-invoice-line-schema.ts#PeppolInvoiceLine': [
    'cbc:ID',
    'cbc:Note',
    'cbc:InvoicedQuantity',
    'cbc:LineExtensionAmount',
    'cbc:AccountingCost',
    'cac:InvoicePeriod',
    'cac:OrderLineReference',
    'cac:DocumentReference',
    'cac:AllowanceCharge',
    'cac:Item',
    'cac:Price',
  ],
  './fields/peppol-invoice-period-schema.ts#PeppolInvoicePeriod': ['cbc:StartDate', 'cbc:EndDate', 'cbc:DescriptionCode'],
  './fields/peppol-legal-monetary-total-schema.ts#PeppolLegalMonetaryTotal': [
    'cbc:LineExtensionAmount',
    'cbc:TaxExclusiveAmount',
    'cbc:TaxInclusiveAmount',
    'cbc:AllowanceTotalAmount',
    'cbc:ChargeTotalAmount',
    'cbc:PrepaidAmount',
    'cbc:PayableRoundingAmount',
    'cbc:PayableAmount',
  ],
  './fields/peppol-line-allowance-charge-schema.ts#PeppolLineAllowance': [
    'cbc:ChargeIndicator',
    'cbc:AllowanceChargeReasonCode',
    'cbc:AllowanceChargeReason',
    'cbc:MultiplierFactorNumeric',
    'cbc:Amount',
    'cbc:BaseAmount',
  ],
  './fields/peppol-line-allowance-charge-schema.ts#PeppolLineCharge': [
    'cbc:ChargeIndicator',
    'cbc:AllowanceChargeReasonCode',
    'cbc:AllowanceChargeReason',
    'cbc:MultiplierFactorNumeric',
    'cbc:Amount',
    'cbc:BaseAmount',
  ],
  './fields/peppol-line-item-schema.ts#PeppolAdditionalItemProperties': ['cbc:Name', 'cbc:Value'],
  './fields/peppol-line-item-schema.ts#PeppolLineItem': [
    'cbc:Description',
    'cbc:Name',
    'cac:BuyersItemIdentification',
    'cac:SellersItemIdentification',
    'cac:StandardItemIdentification',
    'cac:OriginCountry',
    'cac:CommodityClassification',
    'cac:ClassifiedTaxCategory',
    'cac:AdditionalItemProperty',
  ],
  './fields/peppol-line-price-allowance-charge-schema.ts#PeppolLinePriceAllowanceCharge': ['cbc:ChargeIndicator', 'cbc:Amount', 'cbc:BaseAmount'],
  './fields/peppol-line-price-allowance-charge-schema.ts#PriceAllowanceCharge': ['cbc:ChargeIndicator', 'cbc:Amount', 'cbc:BaseAmount'],
  './fields/peppol-line-price-schema.ts#PeppolLinePrice': ['cbc:PriceAmount', 'cbc:BaseQuantity', 'cac:AllowanceCharge'],
  './fields/peppol-order-reference-schema.ts#PeppolOrderReference': ['cbc:ID', 'cbc:SalesOrderID'],
  './fields/peppol-party-legal-entity-schema.ts#PeppolPartyLegalEntity': ['cbc:RegistrationName', 'cbc:CompanyID', 'cbc:CompanyLegalForm'],
  './fields/peppol-party-tax-scheme-schema.ts#PeppolPartyTaxScheme': ['cbc:CompanyID', 'cac:TaxScheme'],
  './fields/peppol-payee-party-schema.ts#PeppolPayeeParty': ['cac:PartyIdentification', 'cac:PartyName', 'cac:PartyLegalEntity'],
  './fields/peppol-payment-means-schema.ts#PeppolCardAccount': ['cbc:PrimaryAccountNumberID', 'cbc:NetworkID', 'cbc:HolderName'],
  './fields/peppol-payment-means-schema.ts#PeppolPayeeFinancialAccount': ['cbc:ID', 'cbc:Name', 'cac:FinancialInstitutionBranch'],
  './fields/peppol-payment-means-schema.ts#PeppolPaymentMandate': ['cbc:ID', 'cac:PayerFinancialAccount'],
  './fields/peppol-payment-means-schema.ts#PeppolPaymentMeans': [
    'cbc:PaymentMeansCode',
    'cbc:PaymentDueDate',
    'cbc:PaymentID',
    'cac:CardAccount',
    'cac:PayeeFinancialAccount',
    'cac:PaymentMandate',
  ],
  './fields/peppol-tax-category-schema.ts#PeppolTaxCategory': ['cbc:ID', 'cbc:Percent', 'cac:TaxScheme'],
  './fields/peppol-tax-representative-schema.ts#PeppolTaxRepresentative': ['cac:PartyName', 'cac:PostalAddress', 'cac:PartyTaxScheme'],
  './fields/peppol-tax-subtotal-category-schema.ts#PeppolTaxSubTotalCategory': [
    'cbc:ID',
    'cbc:Percent',
    'cbc:TaxExemptionReasonCode',
    'cbc:TaxExemptionReason',
    'cac:TaxScheme',
  ],
  './fields/peppol-tax-subtotal-schema.ts#PeppolTaxSubTotal': ['cbc:TaxableAmount', 'cbc:TaxAmount', 'cac:TaxCategory'],
  './fields/peppol-tax-totals-base-schema.ts#PeppolTaxTotal': ['cbc:TaxAmount', 'cac:TaxSubtotal'],
  './peppol-credit-note-schema.ts#PeppolCreditNote': [
    'cbc:CustomizationID',
    'cbc:ProfileID',
    'cbc:ID',
    'cbc:IssueDate',
    'cbc:TaxPointDate',
    'cbc:CreditNoteTypeCode',
    'cbc:Note',
    'cbc:DocumentCurrencyCode',
    'cbc:TaxCurrencyCode',
    'cbc:AccountingCost',
    'cbc:BuyerReference',
    'cac:InvoicePeriod',
    'cac:OrderReference',
    'cac:BillingReference',
    'cac:DespatchDocumentReference',
    'cac:ReceiptDocumentReference',
    'cac:ContractDocumentReference',
    'cac:AdditionalDocumentReference',
    'cac:OriginatorDocumentReference',
    'cac:AccountingSupplierParty',
    'cac:AccountingCustomerParty',
    'cac:PayeeParty',
    'cac:TaxRepresentativeParty',
    'cac:Delivery',
    'cac:PaymentMeans',
    'cac:PaymentTerms',
    'cac:AllowanceCharge',
    'cac:TaxTotal',
    'cac:LegalMonetaryTotal',
    'cac:CreditNoteLine',
  ],
  './peppol-document-response-document-reference-schema.ts#PeppolDocumentResponseDocumentReference': [
    'cbc:ID',
    'cbc:DocumentTypeCode',
    'cbc:VersionID',
  ],
  './peppol-document-response-document-schema.ts#PeppolDocumentResponseDocument': ['cbc:ResponseCode', 'cbc:Description'],
  './peppol-document-response-line-response-content-schema.ts#PeppolDocumentResponseLineResponseContent': [
    'cbc:ResponseCode',
    'cbc:Description',
    'cac:Status',
  ],
  './peppol-document-response-line-response-schema.ts#PeppolDocumentResponseLineResponse': ['cac:LineReference', 'cac:Response'],
  './peppol-invoice-response-document-actual-response-schema.ts#PeppolInvoiceResponseDocumentActualResponseWithStatus': [
    'cbc:ResponseCode',
    'cbc:EffectiveDate',
    'cac:Status',
  ],
  './peppol-invoice-response-document-actual-response-schema.ts#PeppolInvoiceResponseDocumentActualResponseWithoutStatus': [
    'cbc:ResponseCode',
    'cbc:EffectiveDate',
    'cac:Status',
  ],
  './peppol-invoice-response-document-actual-response-status-schema.ts#PeppolInvoiceResponseCondition': ['cbc:AttributeID', 'cbc:Description'],
  './peppol-invoice-response-document-actual-response-status-schema.ts#PeppolInvoiceResponseDocumentActualResponseStatus': [
    'cbc:StatusReasonCode',
    'cbc:StatusReason',
    'cac:Condition',
  ],
  './peppol-invoice-response-schema.ts#PeppolInvoiceResponse': [
    'cbc:CustomizationID',
    'cbc:ProfileID',
    'cbc:ID',
    'cbc:IssueDate',
    'cbc:IssueTime',
    'cbc:Note',
    'cac:SenderParty',
    'cac:ReceiverParty',
    'cac:DocumentResponse',
  ],
  './peppol-invoice-response-schema.ts#PeppolInvoiceResponseDocumentReference': ['cbc:ID', 'cbc:IssueDate', 'cbc:DocumentTypeCode'],
  './peppol-invoice-response-schema.ts#PeppolInvoiceResponseDocumentResponse': [
    'cac:Response',
    'cac:DocumentReference',
    'cac:IssuerParty',
    'cac:RecipientParty',
  ],
  './peppol-invoice-response-schema.ts#PeppolInvoiceResponseDocumentResponseParty': ['cac:PartyIdentification', 'cac:PartyName'],
  './peppol-invoice-response-schema.ts#PeppolInvoiceResponseParty': ['cbc:EndpointID', 'cac:PartyIdentification', 'cac:PartyLegalEntity'],
  './peppol-invoice-response-schema.ts#PeppolInvoiceResponseSenderParty': [
    'cbc:EndpointID',
    'cac:PartyIdentification',
    'cac:PartyLegalEntity',
    'cac:Contact',
  ],
  './peppol-invoice-schema.ts#PeppolInvoice': [
    'cbc:CustomizationID',
    'cbc:ProfileID',
    'cbc:ID',
    'cbc:IssueDate',
    'cbc:DueDate',
    'cbc:InvoiceTypeCode',
    'cbc:Note',
    'cbc:TaxPointDate',
    'cbc:DocumentCurrencyCode',
    'cbc:TaxCurrencyCode',
    'cbc:AccountingCost',
    'cbc:BuyerReference',
    'cac:InvoicePeriod',
    'cac:OrderReference',
    'cac:BillingReference',
    'cac:DespatchDocumentReference',
    'cac:ReceiptDocumentReference',
    'cac:OriginatorDocumentReference',
    'cac:ContractDocumentReference',
    'cac:AdditionalDocumentReference',
    'cac:ProjectReference',
    'cac:AccountingSupplierParty',
    'cac:AccountingCustomerParty',
    'cac:PayeeParty',
    'cac:TaxRepresentativeParty',
    'cac:Delivery',
    'cac:PaymentMeans',
    'cac:PaymentTerms',
    'cac:AllowanceCharge',
    'cac:TaxTotal',
    'cac:LegalMonetaryTotal',
    'cac:InvoiceLine',
  ],
  './peppol-message-level-response-document-response-schema.ts#PeppolMessageLevelResponseDocumentResponse': [
    'cac:Response',
    'cac:DocumentReference',
    'cac:LineResponse',
  ],
  './peppol-message-level-response-schema.ts#PeppolMessageLevelResponse': [
    'cbc:CustomizationID',
    'cbc:ProfileID',
    'cbc:ID',
    'cbc:IssueDate',
    'cbc:IssueTime',
    'cac:SenderParty',
    'cac:ReceiverParty',
    'cac:DocumentResponse',
  ],
} as const;

const modules = import.meta.glob(['./**/*.ts', '!./**/*.spec.ts'], { eager: true }) as Record<string, Record<string, unknown>>;

describe('xsd sequence', () => {
  it.each(Object.entries(expected))('%s serializes its children in UBL sequence order', (key, order) => {
    const [path, name] = key.split('#') as [string, string];
    const mod = modules[path];
    assert(mod);

    const schema = mod[name];
    expect(Schema.isSchema(schema), `${key} exports an Effect Schema`).toBe(true);

    expect(serializedOrder(schema as Schema.Constraint)).toEqual(order);
  });
});
