#!/usr/bin/env node
// fallow-ignore-file security-sink
// Offline CLI script: destination path is provided by the developer invoking it,
// so path.join()/fs.writeFile() targets are operator-controlled, not untrusted input.
import { String } from 'effect';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import pc from 'picocolors';

const typescript = String.String.raw;

const argv = process.argv.slice(2);
if (argv.length === 0) {
  console.log('No arguments provided');
  process.exit(1);
}

if (argv.length > 1) {
  console.log('Too many arguments provided');
  process.exit(1);
}

const destinationPath = argv[0]!;
if (String.isEmpty(destinationPath)) {
  console.log('No destination path provided');
  process.exit(1);
}
await fs.mkdir(destinationPath, { recursive: true });

console.debug(pc.dim(`Generating translations into ${pc.yellow(destinationPath)}`));
// oxlint-disable-next-line import/no-relative-parent-imports
const translations = await import('../assets/translations.json', { with: { type: 'json' } });

const ignored: Array<string> = [
  'countryCodes',
  'currencyCodes',
  'additionalDocumentReferenceCodes',
  'quantityUnitCodes',
  'electronicAddressCodes',
  'icdCodes',
  'documentTypeCodes',
];
for (const entry of Object.values(translations)) {
  for (const [file, value] of Object.entries(entry).filter(([file]) => !ignored.includes(file))) {
    const filename = String.kebabCase(String.capitalize(file));
    const translationVariable = `${file}Translations`;

    const destination = path.join(destinationPath, `${filename}.translations.ts`);

    const content = typescript`
// oxlint-disable
/// Do not edit this file directly.
import { m } from '~/paraglide/messages';

export const ${translationVariable}: Record<string, { text: m.LocalizedString; description: m.LocalizedString }>  = {
${Object.entries(value)
  .map(args => {
    const [key, { text, description }] = args as [string, { text: string; description: string }];
    return `get ["${key}"]() {
    return {
      text: m.${text}(),
      description: m.${description}(),
    }
  }`;
  })
  .join(',\n')}
};`;
    console.log('Writing', pc.yellow(path.relative(destinationPath, destination)));
    await fs.writeFile(destination, content);
    console.log('Wrote  ', pc.yellow(path.relative(destinationPath, destination)));
  }
}
