#!/usr/bin/env node
// fallow-ignore-file security-sink
// Offline CLI script: destination path is provided by the developer invoking it,
// so filesystem targets are operator-controlled, not untrusted input.
import { NodeRuntime, NodeServices } from '@effect/platform-node';
import { Console, Effect, FileSystem, Path, String } from 'effect';
import { Argument, Command } from 'effect/cli';
import pc from 'picocolors';

const typescript = String.String.raw;

// oxlint-disable-next-line import/no-relative-parent-imports
const translations = (await import('../assets/translations.json', { with: { type: 'json' } })).default;
// oxlint-disable-next-line import/no-relative-parent-imports
const pkg = (await import('../package.json', { with: { type: 'json' } })).default;

const ignored: Array<string> = [
  'countryCodes',
  'currencyCodes',
  'additionalDocumentReferenceCodes',
  'quantityUnitCodes',
  'electronicAddressCodes',
  'icdCodes',
  'documentTypeCodes',
];

const command = Command.make(
  'generate-translations',
  {
    destination: Argument.Directory('destination').pipe(
      Argument.withDescription('Directory where the generated *.translations.ts files are written')
    ),
  },
  ({ destination }) =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;

      yield* fs.makeDirectory(destination, { recursive: true });
      yield* Console.debug(pc.dim(`Generating translations into ${pc.yellow(destination)}`));

      for (const [file, value] of Object.entries(translations).filter(([file]) => !ignored.includes(file))) {
        const filename = String.kebabCase(String.capitalize(file));
        const translationVariable = `${file}Translations`;

        const destinationFile = path.join(destination, `${filename}.translations.ts`);

        const content = typescript`
// oxlint-disable
/// Do not edit this file directly.
import { m } from '~/paraglide/messages';

export const ${translationVariable}: Record<string, { text: m.LocalizedString; description: m.LocalizedString }>  = {
${Object.entries(value)
  .map(args => {
    const [key, { text, description }] = args as [string, { text: string; description: string }];
    return `get ["${key}"]() {
    return {
      text: m.${text}(),
      description: m.${description}(),
    }
  }`;
  })
  .join(',\n')}
};`;
        yield* Console.log('Writing', pc.yellow(path.relative(destination, destinationFile)));
        yield* fs.writeFileString(destinationFile, content);
        yield* Console.log('Wrote  ', pc.yellow(path.relative(destination, destinationFile)));
      }
    })
);

Command.run(command, { version: pkg.version }).pipe(Effect.provide(NodeServices.layer), NodeRuntime.runMain);
