import { $ } from 'bun';
/**
 * @effect-diagnostics nodeBuiltinImport:off
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

function formatStringLiteral(value: string): string {
  return JSON.stringify(value);
}

function generateKeyDeclarations({
  sourceName,
  typeName,
  keysName,
  keys,
}: {
  sourceName: string;
  typeName: string;
  keysName: string;
  keys: ReadonlyArray<string>;
}): string {
  const union = keys.map(formatStringLiteral).join(' | ');
  const tuple = keys.map(key => `  ${formatStringLiteral(key)},`).join('\n');

  return `/**
 * Keys of {@link ${sourceName}}.
 */
export type ${typeName} = ${union};
export const ${keysName} = [
${tuple}
] as const satisfies readonly [${typeName}, ...Array<${typeName}>];`;
}

/**
 * @description Generate values and validation rules from https://github.com/OpenPEPPOL/peppol-bis-invoice-3.
 */
async function generateFromPeppol() {
  const peppolTempDir = (await $`mktemp -d /tmp/peppol-XXXXXX`.text()).trim();
  const peppolTempDirPoAcc = (await $`mktemp -d /tmp/peppol-XXXXXX`.text()).trim();

  function generateFileContent({
    variableName,
    content,
    keys,
    version,
    identifier,
    title,
  }: {
    variableName: string;
    content: string;
    keys: ReadonlyArray<string>;
    version?: string;
    identifier: string;
    title: string;
  }): string {
    return `// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by \`scripts/values.ts\`

/**
 * @title ${title}
${version ? ` * @version ${version}` : ''}
 * @see https://docs.peppol.eu/poacc/billing/3.0/codelist/${identifier}/
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${content}
} as const;

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, sourceName: variableName, typeName: `${variableName}Key` })}
`;
  }

  /**
   * @description Generate the values from https://github.com/OpenPEPPOL/peppol-bis-invoice-3.
   */
  async function generateValues() {
    console.log('Cloning PEPPOL BIS Invoice 3 repository to', peppolTempDir);
    await $`git clone --depth 1 https://github.com/OpenPEPPOL/peppol-bis-invoice-3 ${peppolTempDir}`.quiet();

    console.log('Cloning PEPPOL poaccc 3 repository to', peppolTempDirPoAcc);
    await $`git clone --depth 1 https://github.com/OpenPEPPOL/poacc-upgrade-3.git ${peppolTempDirPoAcc}`.quiet();

    const valuePath = path.join(import.meta.dirname, '..', 'src', 'values');
    console.log('Creating value path at', valuePath);
    await $`mkdir -p ${valuePath}`.quiet();

    console.log('--- Starting to process value files ---');
    const generationList = [
      [`${peppolTempDir}/structure/codelist/ISO3166-1_Alpha2.xml`, 'country-code.generated.ts', 'countryCodes'],
      [`${peppolTempDir}/structure/codelist/ISO4217_2015.xml`, 'currency-code.generated.ts', 'currencyCodes'],
      [`${peppolTempDir}/structure/codelist/MimeCode.xml`, 'mime-codes.generated.ts', 'mimeCodes'],
      // [`${peppolTempDir}/structure/codelist/SEPA.xml`, 'sepa-codes.generated.ts', 'sepaCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL1001-cn.xml`, 'credit-notes-type-codes.generated.ts', 'creditNoteTypeCodes', 'documentTypeCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL1001-inv.xml`, 'invoice-type-codes.generated.ts', 'invoiceTypeCodes', 'documentTypeCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL1153.xml`, 'additional-document-reference-codes.generated.ts', 'additionalDocumentReferenceCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL2005.xml`, 'vat-dates.generated.ts', 'vatDateCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL4461.xml`, 'payment-means-codes.generated.ts', 'paymentMeansCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL5189.xml`, 'allowance-charge-reason-codes.generated.ts', 'allowanceChargeReasonCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL5305.xml`, 'duty-tax-fee-categories.generated.ts', 'dutyTaxFeeCategories'],
      [`${peppolTempDir}/structure/codelist/UNCL7143.xml`, 'item-classification-code.generated.ts', 'itemClassificationCodes'],
      [`${peppolTempDir}/structure/codelist/UNCL7161.xml`, 'charge-reason-codes.generated.ts', 'chargeReasonCodes'],
      [`${peppolTempDir}/structure/codelist/UNECERec20-11e.xml`, 'quantity-unit-codes.generated.ts', 'quantityUnitCodes'],
      [`${peppolTempDir}/structure/codelist/VATEX.xml`, 'vatex-codes.generated.ts', 'vatexCodes'],
      [`${peppolTempDir}/structure/codelist/eas.xml`, 'eas-codes.generated.ts', 'electronicAddressCodes'],
      [`${peppolTempDir}/structure/codelist/icd.xml`, 'icd-codes.generated.ts', 'icdCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/UNCL1001.xml`, 'document-type-codes.generated.ts', 'documentTypeCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/UNCL4343.xml`, 'application-response-type-codes.generated.ts', 'applicationResponseTypeCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/UNCL4343-T111.xml`, 'invoice-status-codes.generated.ts', 'invoiceStatusCodes'],
      [`${peppolTempDirPoAcc}/structure/codelist/OPStatusAction.xml`, 'op-status-action.generated.ts', 'opStatusAction'],
      [`${peppolTempDirPoAcc}/structure/codelist/OPStatusReason.xml`, 'op-status-reason.generated.ts', 'opStatusReason'],
    ] as const;

    for (const [peppolFileName, outputFileName, variableName] of generationList) {
      console.log('Processing', peppolFileName, '->', outputFileName);
      const title = (await $`cat ${peppolFileName} | xq ".CodeList.Title"`.text()).replaceAll('"', '').trim();
      const identifier = (await $`cat ${peppolFileName} | xq ".CodeList.Identifier"`.text()).replaceAll('"', '').trim();
      const version = (await $`cat ${peppolFileName} | xq ".CodeList.Version"`.text()).replaceAll('"', '').trim();
      const keys = (await $`cat ${peppolFileName} | xq ".CodeList.Code | map(.Id | tostring)"`.json()) as Array<string>;
      const content =
        await $`cat ${peppolFileName} | xq ".CodeList.Code[]" | jq -r '(if has("Description") and .Description != null then "/**\n* " + (.Description | sub("\n"; ""; "g") | sub(" {2,}"; " "; "g")) + "\n*/\n" else "" end) + "\"" + .Id + "\": \"" + (.Name | sub("\n"; ""; "g") | sub("\""; ""; "g") | sub(" {2,}"; " "; "g")) + "\","'`.text();

      console.log('Writing to', outputFileName);
      await fs.writeFile(path.join(valuePath, outputFileName), generateFileContent({ content, identifier, keys, title, variableName, version }));
      console.log('Finished writing', outputFileName);
    }

    console.log('--- All value files processed ---');
  }

  try {
    await generateValues();
  } finally {
    console.log('Cleaning up temporary directory', peppolTempDirPoAcc);
    await $`rm -rf ${peppolTempDirPoAcc}`.quiet();
    console.log('Cleaning up temporary directory', peppolTempDir);
    await $`rm -rf ${peppolTempDir}`.quiet();
  }
}

async function generateEdec() {
  const version = 'v9.7';
  const edecTempDir = (await $`mktemp -d /tmp/edec-XXXXXX`.text()).trim();

  console.log('Cloning PEPPOL BIS Invoice 3 repository to', edecTempDir);
  await $`git clone --depth 1 https://github.com/OpenPEPPOL/edec-codelists ${edecTempDir}`.quiet();
  const valuePath = path.join(import.meta.dirname, '..', 'src', 'values');
  console.log('Creating value path at', valuePath);
  await $`mkdir -p ${valuePath}`.quiet();
  console.log('Processing EDEC values');
  const publicationPath = path.join(edecTempDir, 'publication', version);
  // const generationList = [
  //   [`Peppol Code Lists - SPIS Use Case ${version}.json`, 'spi-use-cases.generated.ts', 'spiUseCases'],
  //   [`Peppol Code Lists - Transport profiles ${version}.json`, 'spi-use-cases.generated.ts', 'spiUseCases'],
  // ] as const;

  async function generateDocumentTypes() {
    console.log('Processing document types');
    const sourceFileName = `Peppol Code Lists - Document types ${version}.json`;
    const generatedFileName = 'document-type.generated.ts';
    const variableName = 'documentTypes';
    const documentTypesContent = JSON.parse(await fs.readFile(path.join(publicationPath, sourceFileName), 'utf-8')) as {
      version: string;
      values: Array<Record<string, string>>;
    };

    const grouped = documentTypesContent.values.reduce<Record<string, Array<Record<string, string>>>>((prev, curr) => {
      (prev[curr['scheme']!] ??= []).push(curr);
      return prev;
    }, {});
    const tableKeys = Object.keys(grouped);
    // this is the previous code for generation
    // /**
    //  * @title Peppol Document Types
    //  * @version ${documentTypesContent.version}
    //  * @enum
    //  * @category Peppol Values
    //  */
    // export const ${variableName} = {
    // ${Object.entries(grouped).map(([key, value]) => `"${key}": {${value.map(value => `/**
    // * @name \`${value['name']}\`
    // * @scheme \`${value['scheme']}\`
    // * @category ${value['category']}
    // * @domain ${value['domain-community']}
    // * @version ${value['bis-version']}
    // * @since ${value['initial-release']}${value['state'] !== 'active' ? '\n* @deprecated' : ''}${value['comment'] ? `\n* @remark ${value['comment'].replace(/[\n\r]/g, '\n* ')}` : ''}
    // */
    // "${value['value']}": ${JSON.stringify({ name: value['name'], category: value['category'], community: value['domain-community'], processIds: value['process-ids'], })}`) .join(',\n')}}`)
    // .join(',\n')}
    // } as const;

    await fs.writeFile(
      path.join(valuePath, generatedFileName),
      `// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by \`packages/www/scripts/values.ts\`

export const ${variableName}Table = {
${Object.entries(grouped)
  .map(([key, value]) => `  "${key}": [ ${value.map(v => `"${v['value']}"`).join(', ')} ]`)
  .join(',\n')}
} as const;

${generateKeyDeclarations({
  keys: tableKeys,
  keysName: `${variableName}TableKeys`,
  sourceName: `${variableName}Table`,
  typeName: `${variableName}TableKey`,
})}

export const ${variableName}Scheme = [
${tableKeys.map(key => `  "${key}",`).join('\n')}
] as const;


export const ${variableName}ProcessIds = {
${Object.entries(grouped)
  .map(([key, value]) => value.map(v => `"${key}::${v['value']}": ${JSON.stringify(v['process-ids'])}`).join(',\n'))
  .join(',\n')}
} as const;

export const ${variableName}List = [
${Object.entries(grouped)
  .flatMap(([key, value]) => value.map(v => `"${key}::${v['value']}"`).join(',\n'))
  .join(',\n')}
] as const;

/**
 * The list of elements that are deprecated.
 */
export const deprecated${variableName} = [
${documentTypesContent.values
  .filter(value => value['state'] !== 'active')
  .map(value => `  "${value['value']}",`)
  .join('\n')}
] as const;
`
    );
  }

  async function generateParticipantIdentifierSchemes() {
    console.log('Processing participant identifier schemes');

    const sourceFileName = `Peppol Code Lists - Participant identifier schemes ${version}.json`;
    const generatedFileName = 'participant-identifier-schemes.generated.ts';
    const variableName = 'participantIdentifierSchemes';
    const documentTypesContent = JSON.parse(await fs.readFile(path.join(publicationPath, sourceFileName), 'utf-8')) as {
      version: string;
      values: Array<Record<string, string | undefined>>;
    };
    const keys = documentTypesContent.values.map(value => value['iso6523']).filter((value): value is string => Boolean(value));

    await fs.writeFile(
      path.join(valuePath, generatedFileName),
      `// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by \`packages/www/scripts/values.ts\`

/**
 * @title Peppol Participant Identifier Schemes
 * @version ${documentTypesContent.version}
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${documentTypesContent.values
  .map(value => {
    const examples = value['examples']
      ? `\n* @example \n* ${value['examples']
          ?.split('\n')
          .map(ex => `\`${ex.trim()}\``)
          .join('\n* ')}`
      : '';

    const validations = value['validation-rules']
      ? `\n* @validation \n* ${value['validation-rules']
          .split('\n')
          .map(rule => {
            const r = rule.trim();
            if (r.startsWith('RegEx: ')) {
              return `\`\`\`regex\n* ${r.slice(7)}\n* \`\`\``;
            }
            return r;
          })
          .join('\n* ')}`
      : '';

    return `/**
* @name \`${value['scheme-name']?.replace('\n', ' ')}\`
* @country \`${value['country']}\`
* @since ${value['initial-release']}${value['state'] !== 'active' ? '\n* @deprecated' : ''}${examples}${validations}
*/
"${value['iso6523']}": "${value['schemeid']}",`;
  })
  .join('\n')}
} as const;

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, sourceName: variableName, typeName: `${variableName}Key` })}

/**
 * The list of elements that are deprecated.
 */
export const deprecated${variableName} = [
${documentTypesContent.values
  .filter(value => value['state'] !== 'active')
  .map(value => `  "${value['iso6523']}",`)
  .join('\n')}
] as const;
`
    );
  }

  async function generateProcess() {
    console.log('Processing process schemes');
    const sourceFileName = `Peppol Code Lists - Processes ${version}.json`;
    const generatedFileName = 'processes.generated.ts';
    const variableName = 'processes';

    const documentTypesContent = JSON.parse(await fs.readFile(path.join(publicationPath, sourceFileName), 'utf-8')) as {
      version: string;
      values: Array<Record<string, string | undefined>>;
    };

    const grouped = documentTypesContent.values.reduce<Record<string, Array<Record<string, string | undefined>>>>((prev, curr) => {
      (prev[curr['scheme']!] ??= []).push(curr);
      return prev;
    }, {});
    const keys = Object.keys(grouped);

    await fs.writeFile(
      path.join(valuePath, generatedFileName),
      `// oxlint-disable sort-keys
/// Do not edit this file directly. It is generated by \`packages/www/scripts/values.ts\`

/**
 * @title Peppol Participant Identifier Schemes
 * @version ${documentTypesContent.version}
 * @enum
 * @category Peppol Values
 */
export const ${variableName} = {
${Object.entries(grouped)
  .map(([key, value]) => `"${key}": [${value.map(value => JSON.stringify(value['value'])).join(',')}]`)
  .join(',\n')}
} as const;

${generateKeyDeclarations({ keys, keysName: `${variableName}Keys`, sourceName: variableName, typeName: `${variableName}Key` })}

export const ${variableName}Scheme = [
${keys.map(key => `  "${key}",`).join('\n')}
] as const;

export const ${variableName}List = [
${Object.entries(grouped)
  .flatMap(([key, value]) => value.map(v => `"${key}::${v['value']}"`).join(',\n'))
  .join(',\n')}
] as const;

/**
 * The list of elements that are deprecated.
 */
export const deprecated${variableName} = [
${documentTypesContent.values
  .filter(value => value['state'] !== 'active')
  .map(value => `  "${value['value']}",`)
  .join('\n')}
] as const;
`
    );
  }

  await generateDocumentTypes();
  await generateParticipantIdentifierSchemes();
  await generateProcess();
}

await generateFromPeppol();
await generateEdec();

console.log('Running oxlint --fix on generated files');
await $`bunx oxlint --fix ${import.meta.dirname}`.quiet();
